### ISSUE TITLE
Generate SBOM

### ISSUE THREAD

**Issue by achrefbensaad** [kubearmor/KubeArmor#1012]
We would like to generate SBOM (Software Bill Of Materials) for KubeArmor for each release.

We can use [syft](https://github.com/anchore/syft) github action for that purpose [link](https://github.com/anchore/sbom-action)

- [ ] update CI to generate SBOM for each release and add it as an asset in the release manifest.

**Comment by slayer321** [comment]
Hey @achrefbensaad , I did like to work on this issue. can you assign it to me
As you mentioned that we need to update the CI .. but after seeing the current CI setup for the project I think we will need a different file for SBOM(ci-release-sbom.yaml) .. something like below 
```
name: SBOM

on:
  release:
    types: [published]

jobs:
  sbom:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref_name }}
      - name: Anchore SBOM Action
        uses: anchore/sbom-action@v0.12.0
        with:
          format: cyclonedx-json
```
can you confirm if this is a correct way of doing it?
