### ISSUE TITLE
Network policies fails to apply (Apparmor)

### ISSUE THREAD

**Issue by achrefbensaad** [kubearmor/KubeArmor#1019]
## Bug Report

**General Information**

- lsm: AppArmor

**To Reproduce**

1. Apply this policy
``` yaml
apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: pol02
spec:
  action: Block
  network:
    matchProtocols:
    - protocol: TCP
  selector:
    matchLabels:
      app: dvwa-web
  severity: 1
```

**Expected behavior**

A block network policy should be applied

** Actual behavior**

The policy cannot be applied

![image](https://user-images.githubusercontent.com/25206910/208036812-fe479967-ed78-437f-90d3-38445258122a.png)

**Proposed fix**

In apparmor profile generation, force the protocol to lower case.
