### ISSUE TITLE
KubeArmor not generating alert for policy violation if default posture is audit

### ISSUE THREAD

**Issue by rksharma95** [kubearmor/KubeArmor#1038]
## Bug Report

**General Information**

- Environment description `k3s`
- Kernel version `5.15.0-56-generic`
- Orchestration system version in use `Major:"1", Minor:"25", GitVersion:"v1.25.3+k3s1"`
- enforcer: `apparmor`

**To Reproduce**
1. Run Kubearmor with default posture as `audit` for `File`, `Network` and `Capabilities`
 - change values for default posture in the makefile [here](https://github.com/kubearmor/KubeArmor/blob/main/KubeArmor/Makefile#L46)
 - run kubearmor with `make run`
2. Apply the ubuntu deployment:
```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: partialyannotated
  # annotations:
    # "kubearmor-file-posture": "audit"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: partialyannotated-deployment
  namespace: partialyannotated
  labels:
    deployment: partialyannotated
spec:
  replicas: 1
  selector:
    matchLabels:
      container: partialyannotated
  template:
    metadata:
      labels:
        container: partialyannotated
    spec:
      containers:
      - name: ubuntu-1
        image: kubearmor/ubuntu-w-utils:0.1
```
3. Apply the policy
```yaml
apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-partialyannotated-allow
  namespace: partialyannotated
spec:
  severity: 8
  selector:
    matchLabels:
      container: partialyannotated
  network:
    matchProtocols:
    - protocol: tcp
      fromSource:
      - path: /usr/bin/curl
  process:
    matchDirectories:
    - dir: /bin/ # required to change root to user1
      recursive: true
    - dir: /usr/bin/ # used in changing accounts
      recursive: true
  file:
    matchPaths:
    - path: /root/.bashrc # used by root
    - path: /root/.bash_history # used by root
    - path: /dev/tty
    matchDirectories:
    - dir: /credentials/
    - dir: /etc/ # used by root (coarse-grained way)
      recursive: true
    - dir: /proc/ # used by root (coarse-grained way)
      recursive: true
  action:
    Allow
```
4. Observe the KubeArmor telemetry
```
karmor log --gRPC=localhost:32767
```
5. Simulate policy violation
```
POD_NAME=$(kubectl get pods -n partialyannotated -l "container=partialyannotated" -o jsonpath='{.items[0].metadata.name}') && kubectl -n partialyannotated exec -it $POD_NAME -- bash -c "cat /credentials/keys/priv.key"
```
**Expected behavior**

KubeArmor should generate an alert with data `PolicyName: DefaultPosture`,`Action: Audit`, and `Result: Passed`. 
But we're not getting the alert.

**Screenshots**
