### ISSUE TITLE
Need a security policy validator and supporting per-field/rule action/severity

### ISSUE THREAD

**Issue by nam-jaehyun** [kubearmor/KubeArmor#104]
When we apply security policies based on KubeArmor's CRD, we need to check two things.

1. Syntax

CRD basically contains syntax validation logic for each field, but it can only check input types or patterns.

2. Semantics

CRD doesn't contain any validations for semantics, meaning that a user needs to properly define security policies without semantics errors.

Here are some examples.
- 'ownerOnly' works with the Allow action.
- 'recursive' is only effective with directories, not paths.
- NodeSelector cannot be defined with selector.

As a result, we need a security policy validator at the Kubernetes side in order to check syntax and semantics errors
as soon as some policies are applied into Kubernetes and before they are detected by KubeArmor.

The validator might be implemented as a custom controller along with the CRD.

**Comment by nyrahul** [comment]
## Supporting per-field/rule action/severity

KubeArmor currently allows specific `action`/`severity` on per policy only. If multiple rules of different types exist in the same policy then KubeArmor does not support specifying different action/severity on per-rule type.

In the future, we should support per-field/per-rule/per-policy. Check following example to be supported.

```
apiVersion: security.accuknox.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-group-1-proc-path-block
  namespace: multiubuntu
spec:
  selector:
    matchLabels:
      group: group-1
  process:
    matchPaths:   # Example of multiple fields with associated action/severity
    - path: /bin/sleep
      severity: 5
      action: Block
    - path: /bin/cat
      severity: 3
      action: Audit
  file:
    action: audit
    severity: 3
    matchDirectories: # The below field does not have an action/severity, thus the action/severity in context of rule will be used
      - dir: /credentials/
        recursive: true
  network:
    matchProtocols: # The below field and this rule both do not have an action/severity. In this case policy specific action/severity will be used.
    - protocol: tcp
  severity: 6
  action: Block
```
