### ISSUE TITLE
Generating Kyverno policies dynamically using KubeArmor

### ISSUE THREAD

**Issue by Vyom-Yadav** [kubearmor/KubeArmor#1106]
# Generating Kyverno policies dynamically using KubeArmor

The aim of the project is to integerate Kyverno and KubeArmor by generating Kyverno policies thorugh the runtime data that KubeArmor can provide.

### 1. Detecting unused `ServiceAccount` token mounted onto pods.

The idea is to detect whether any read accesses have been made to the service account token or not (using KubeArmor). If not, then turn `automountServiceAccountToken` to `false`.

Policy:
```yaml
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: restrict-automount-sa-token
  annotations:
    policies.kyverno.io/title: Restrict Auto-Mount of Service Account Tokens
    policies.kyverno.io/severity: medium
    policies.kyverno.io/minversion: 1.6.0
    policies.kyverno.io/description: >-
      If the Service Account Token is not used by a pod, then it should not be
      automounted.    
spec:
  validationFailureAction: audit
  background: true
  rules:
  - name: validate-automountServiceAccountToken
    match:
      any:
      - resources:
          kinds:
          - Pod
    preconditions:
      all:
      - key: "{{ request.operation || 'BACKGROUND' }}"
        operator: NotEquals
        value: DELETE
    validate:
      message: "Auto-mounting of Service Account tokens is not allowed."
      pattern:
        spec:
          automountServiceAccountToken: "false"
```

 - [x] Can be implemented with current version of KubeArmor
 - [ ] Enhancement required in KubeAmor (mention "how" to do that enhancement too)
 - [ ] Not Possible

### 2. Dropping not required `securityContext.capabilities` for a container.

As KubeArmor cannot at present pinpoint all the capabilities required by a container, we will be dropping capabilities than can be detected by KubeArmor and isn't used.

Policy:
```yaml
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: disallow-capabilities
  annotations:
    policies.kyverno.io/title: Disallow Capabilities
    policies.kyverno.io/severity: medium
    kyverno.io/kyverno-version: 1.6.0
    policies.kyverno.io/minversion: 1.6.0
    kyverno.io/kubernetes-version: "1.22-1.23"
    policies.kyverno.io/description: >-
            Drop capabilities unwanted by a container.
spec:
  validationFailureAction: Audit
  background: true
  rules:    
    - name: drop-unwanted-capabilities
      match:
        any:
        - resources:
            kinds:
              - Pod
      preconditions:
        all:
        - key: "{{ request.operation || 'BACKGROUND' }}"
          operator: NotEquals
          value: DELETE
      validate:
        message: >-
          Capabilities that are not used should be dropped.          
        deny:
          conditions:
            all:
            - key: ["CAP-1", "CAP-2"]
              operator: AnyNotIn
              value: "{{ request.object.spec.[ephemeralContainers, initContainers, containers][].securityContext.capabilities.drop[] }}"
```

 - [x] Can be implemented with current version of KubeArmor
 - [ ] Enhancement required in KubeAmor (mention "how" to do that enhancement too)
 - [ ] Not Possible

### 3. Disallowed syscalls.

The idea is to get all the syscalls that a pod does not require and can be safely dropped, create a seccomp policy with data from KubeArmor, store it at some place, and create a policy enforcing usage of that seccomp profile.

`seccomp-policy.json` (generated by information from KubeArmor)
```json
{
    "defaultAction": "SCMP_ACT_ALLOW",
    "architectures": [
        "SCMP_ARCH_X86_64",
        "SCMP_ARCH_X86",
        "SCMP_ARCH_X32"
    ],
    "syscalls": [
        {
            "names": [
                "accept4",
                "epoll_wait"
                "pselect6",
                "futex",
                "set_tid_address",
                "setitimer",
                "writev"
            ],
            "action": "SCMP_ACT_ERRNO"
        }
    ]
}
```

Policy basic:
```yaml
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: restrict-seccomp
  annotations:
    policies.kyverno.io/title: Restrict Seccomp
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Pod
    kyverno.io/kyverno-version: 1.6.0
    kyverno.io/kubernetes-version: "1.22-1.23"
    policies.kyverno.io/description: >-
      This policy, requiring Kubernetes v1.19 or later, ensures that seccomp is 
      set to `Localhost` with localhostProfile to the one generated by KubeArmor.      
spec:
  background: true
  validationFailureAction: audit
  rules:
    - name: check-seccomp
      match:
        any:
        - resources:
            kinds:
              - Pod
      validate:
        message: >-
          The fields spec.containers[*].securityContext.seccompProfile.type,
          must be set to `Localhost` with `localhostProfile` to the 
          one generated by KubeArmor.
        pattern:
          spec:
            containers:
            - securityContext:
                seccompProfile:
                  type: "Localhost"
                  localhostProfile: profile/generated-by-kubearmor.json
```
 - [ ] Can be implemented with current version of KubeArmor
 - [x] Enhancement required in KubeAmor (mention "how" to do that enhancement too)
 - [ ] Not Possible

### 4. Read-Only Root Filesystem

The idea is to generate a policy based on whether the processes in the container just read from the root filesystem or write to it too.

Policy:
```yaml
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-ro-rootfs
  annotations:
    policies.kyverno.io/title: Require Read-Only Root Filesystem
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/minversion: 1.6.0
    policies.kyverno.io/description: >-
      A read-only root file system helps to enforce an immutable infrastructure strategy;
      the container only needs to write on the mounted volume that persists the state.
      An immutable root filesystem can also prevent malicious binaries from writing to the
      host system. This policy validates that containers define a securityContext
      with `readOnlyRootFilesystem: true`.      
spec:
  validationFailureAction: audit
  background: true
  rules:
  - name: validate-readOnlyRootFilesystem
    match:
      any:
      - resources:
          kinds:
          - Pod
    validate:
      message: "Root filesystem must be read-only."
      pattern:
        spec:
          containers:
          - securityContext:
              readOnlyRootFilesystem: true
```

 - [x] Can be implemented with current version of KubeArmor
 - [ ] Enhancement required in KubeAmor (mention "how" to do that enhancement too)
 - [ ] Not Possible

### 5. Already in use list of `hostPort`

The idea is to generate a policy based on `spec.containers[*].ports[*].hostPort`. The policy will include a list of host ports that are already in use (not including 30000-32767). The policy can be generated statically from pod manifests and don't require runtime information from KubeArmor. This would prevent two different administrators from using same `hostPort` by mistake.

Pod:
```yaml
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
  name: nginx
spec:
  containers:
  - image: nginx
    name: nginx
    ports:
      - containerPort: 80
        hostPort: 8081
```

Policy basic:
```yaml
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: disallow-host-ports
  annotations:
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Pod
    kyverno.io/kyverno-version: 1.6.0
    policies.kyverno.io/minversion: 1.6.0
    kyverno.io/kubernetes-version: "1.22-1.23"
    policies.kyverno.io/description: >-
      Access to host ports allows potential snooping of network traffic and should not be
      allowed, or at minimum restricted to a known list. This policy ensures the `hostPort`
      field is set to one in the designated list.       
spec:
  validationFailureAction: audit
  background: true
  rules:
    - name: host-port
      match:
        any:
        - resources:
            kinds:
              - Pod
      validate:
        message: >-
                    The host port is already in use by another pod.
        deny:
          conditions:
            all:
            - key: "{{ request.object.spec.[ephemeralContainers, initContainers, containers][].ports[].hostPort }}"
              operator: AnyIn
              value: [8081]
```
Another way to create this policy would be to create a `ConfigMap` of of used ports and the policy can in turn read the `ConfigMap` for validation.

 - [ ] Can be implemented with current version of KubeArmor
 - [ ] Enhancement required in KubeAmor (mention "how" to do that enhancement too)
 - [ ] Not Possible

### 6. Limit `hostPath` Volumes to Specific Directories
 
From https://kyverno.io/policies/other/limit-hostpath-vols/limit-hostpath-vols/

```yaml
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: limit-hostpath-vols
  annotations:
    policies.kyverno.io/title: Limit hostPath Volumes to Specific Directories
    policies.kyverno.io/category: Other
    policies.kyverno.io/severity: medium
    policies.kyverno.io/minversion: 1.6.0
    kyverno.io/kyverno-version: 1.6.2
    kyverno.io/kubernetes-version: "1.23"
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/description: >-
      hostPath volumes consume the underlying node's file system. If hostPath volumes
      are not to be universally disabled, they should be restricted to only certain
      host paths so as not to allow access to sensitive information. This policy ensures
      the only directory that can be mounted as a hostPath volume is /data. It is strongly
      recommended to pair this policy with a second to ensure readOnly
      access is enforced preventing directory escape.      
spec:
  background: false
  validationFailureAction: audit
  rules:
  - name: limit-hostpath-to-slash-data
    match:
      any:
      - resources:
          kinds:
          - Pod
    preconditions:
      all:
      - key: "{{ request.object.spec.volumes[?hostPath] | length(@) }}"
        operator: GreaterThanOrEquals
        value: 1
      - key: "{{request.operation || 'BACKGROUND'}}"
        operator: AnyIn
        value:
        - CREATE
        - UPDATE
    validate:
      message: hostPath volumes are confined to /data.
      foreach:
      - list: "request.object.spec.volumes[?hostPath].hostPath"
        deny:
          conditions:
            any:
            - key: "{{ element.path  | to_string(@) | split(@, '/') | [1] }}"
              operator: NotEquals
              value: data
```

Similar to point 5, this can also be generated statically from the pod manifest.

 - [ ] Can be implemented with current version of KubeArmor
 - [ ] Enhancement required in KubeAmor (mention "how" to do that enhancement too)
 - [ ] Not Possible

### 1. Specifying exact `securityContext.seLinuxOptions` for a pod

The idea is to specify the exact `level` for `seLinuxOptions` from data provided by KubeArmor.
```yaml
...
securityContext:
  seLinuxOptions:
    level: "s0:c123,c456"
```

 - [ ] Can still be implemented?

### 2. Specifying exact `securityContext.sysctls` for a pod

The idea is to specify the exact kernel parameters for a pod from data provided by KuberAmor.

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: sysctl-example
spec:
  securityContext:
    sysctls:
    - name: kernel.shm_rmid_forced
      value: "0"
    - name: net.core.somaxconn
      value: "1024"
    - name: kernel.msgmax
      value: "65536"
  ...
```
 - [ ] Can still be implemented?
