### ISSUE TITLE
Docker Compose Deployment for securing unorchestrated container

### ISSUE THREAD

**Issue by daemon1024** [kubearmor/KubeArmor#1341]
## Feature Request

**Short Description**

We currently have a systemd deployment which helps manage unorchestrated containers and host policies
Ref https://github.com/kubearmor/KubeArmor/blob/main/getting-started/kubearmor_vm.md

**Is your feature request related to a problem? Please describe the use case.**
Folks might want to just start another container and not deal with the package management hassle to start systemd service.

**Describe the solution you'd like**

Docker Compose File and Documentation to run KubeArmor directly with docker.

Here's how you can do it

```sh
docker run -v /opt/kubearmor/BPF:/opt/kubearmor/BPF --privileged kubearmor/kubearmor-init:stable

# Followed by

docker run -v /opt/kubearmor/BPF:/opt/kubearmor/BPF -v /sys/fs/bpf:/sys/fs/bpf -v /sys/fs/bpf:/sys/fs/bpf -v /sys/kernel/security:/sys/kernel/security -v /sys/kernel/debug:/sys/kernel/debug  -v /var/run/containerd/containerd.sock:/var/run/containerd/containerd.sock -v /run/containerd:/run/containerd -v /var/lib/docker:/var/lib/docker --privileged  --pid=host --ipc=host --net=host kubearmor/kubearmor:latest -k8s=false
```

This is privielged but we won't need the privileges and can mention exact capabilities as well in the docker compose file.

**Comment by yashvardhanmishra** [comment]
hey @daemon1024 . Could you pls assign this to me , i would like to work on this

**Comment by sarthaksarthak9** [comment]
I would love to solve this issue @daemon1024 Pls assign this issue to me

**Comment by sarthaksarthak9** [comment]
#1343

**Comment by yashvardhanmishra** [comment]
hey @daemon1024 can you please guide me related to the capabilities  which is to mention ?

**Comment by sarthaksarthak9** [comment]
@yashvardhanmishra I am really sorry I by mistake link my pull request with other issue and you haven't get noticed and created pull request

**Comment by daemon1024** [comment]
Folks @yashvardhanmishra @sarthaksarthak9 Thanks a lot for the interest and raising the PRs already. Both of them look duplicated efforts, let's handle it in a single PR. 

@sarthaksarthak9 why don't you help review @yashvardhanmishra PR since he wanted to work on the issue first. I appreciate both of your efforts a lot so thank you.

**Comment by sarthaksarthak9** [comment]
> Folks @yashvardhanmishra @sarthaksarthak9 Thanks a lot for the interest and raising the PRs already. Both of them look duplicated efforts, let's handle it in a single PR.
> 
> @sarthaksarthak9 why don't you help review @yashvardhanmishra PR since he wanted to work on the issue first. I appreciate both of your efforts a lot so thank you.

yah sure why not

**Comment by daemon1024** [comment]
This is an open issue again

**Comment by krisharyan** [comment]
I want to work on this issue. Please assign this issue to me

**Comment by navin772** [comment]
@daemon1024 I'm trying to solve this.
The docker compose file works and starts kubearmor after kubearmor-init has finished running. 

But the policy enforcement doesn't seem to work.
For example, I created container for wordpress-mysql via the docker-compose file:

```
services:
  wordpress:
    container_name: wordpress-mysql
    image: wordpress:latest
    ports:
      - 80:80
    restart: always
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
      - WORDPRESS_DB_NAME=wordpress
volumes:
  db_data:
```
The creation of the container is successfully detected by KubeArmor (which is running as a docker container).

Then, I applied a block policy via `karmor vm policy add ksp-wordpress-block-policy.yaml` which is:

```
apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-block-policy
spec:
  severity: 3
  selector:
    matchLabels:
      kubearmor.io/container.name: wordpress-mysql
  process:
    matchPaths:
    - path: /usr/bin/apt
    - path: /usr/bin/apt-get

      # apt update
      # apt-get update

  action:
    Block
```
The security policy is also detected by KubeArmor - 

```
2024-05-24 17:31:01.656355      INFO    Started to monitor container security policies on gRPC
2024-05-24 17:31:01.656427      INFO    Started to serve gRPC-based log feeds
2024-05-24 17:31:01.656437      INFO    Initialized KubeArmor
2024-05-24 17:31:01.656473      WARN    Policies dir not found for restoration


2024-05-24 17:31:16.784291      INFO    Detected a Container Security Policy (added/container_namespace/ksp-block-policy)
```

But now if I exec into the `wordpress-mysql` container and run `apt update` it isn't blocking that!
