### ISSUE TITLE
Policy name not being matched for readonly policies

### ISSUE THREAD

**Issue by Ankurk99** [kubearmor/KubeArmor#1370]
## Bug Report

**Description**
For readOnly based policies the generated alerts do not display the corresponding policy name that was matched; instead, they show `DefaultPosture`. 
Enforcement is running fine.

**General Information**
- Environment description: AKS

**To Reproduce**
- Apply the following readOnly rules based policy:

```
apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: harden-percona-server-mongodb-operator-file-integrity-monitoring
  namespace: accuknox-dev-mongodb
spec:
  action: Block
  file:
    matchDirectories:
    - dir: /sbin/
      readOnly: true
      recursive: true
    - dir: /usr/bin/
      readOnly: true
      recursive: true
    - dir: /usr/lib/
      readOnly: true
      recursive: true
    - dir: /usr/sbin/
      readOnly: true
      recursive: true
    - dir: /bin/
      readOnly: true
      recursive: true
    - dir: /boot/
      readOnly: true
      recursive: true
  message: Detected and prevented compromise to File integrity
  selector:
    matchLabels:
      name: percona-server-mongodb-operator
  severity: 1
```
- check kubearmor alerts: `karmor log`

**Current Output**
PolicyName is DefaultPosture

```
  "PodName": "percona-server-mongodb-operator-5fc4f8d688-t67n6",
  "Labels": "name=percona-server-mongodb-operator",
  "ContainerID": "4cf92782a4e07379eca5aea49ac5feb68fa8ef1ebddb680ef3a7e3f2b3e27aa9",
  "ContainerName": "percona-server-mongodb-operator",
  "ContainerImage": "docker.io/percona/percona-server-mongodb-operator:1.13.0@sha256:7137ee6ff918bd2366033f198f2919e7aa291ae3b76460e267896bf052251837",
  "HostPPID": 9074,
  "HostPID": 12927,
  "PPID": 121,
  "PID": 131,
  "UID": 2,
  "ParentProcessName": "/usr/bin/bash",
  "ProcessName": "/usr/bin/coreutils",
  "PolicyName": "DefaultPosture",
  "Type": "MatchedPolicy",
  "Source": "/usr/bin/touch t",
  "Operation": "File",
  "Resource": "t",
  "Data": "syscall=SYS_OPENAT fd=-100 flags=O_WRONLY|O_CREAT|O_NOCTTY|O_NONBLOCK",
  "Enforcer": "BPFLSM",
  "Action": "Block",
  "Result": "Permission denied"
}
```

**Expected behavior**
The policy name should match the applied policy name, i.e `PolicyName: harden-percona-server-mongodb-operator-file-integrity-monitoring`
