### ISSUE TITLE
{KubeArmor VM/BareMetal } Host policies with matchPath and matchDirectory defined together are not working as expected. 

### ISSUE THREAD

**Issue by Chirag-CG** [kubearmor/KubeArmor#1436]
## Bug Report

**General Information**

- Environment description : VBOX - UbuntuServer 22.02 Image, VM installation using this guide->(https://github.com/kubearmor/KubeArmor/blob/main/getting-started/kubearmor_vm.md)
- Kernel version = Linux master 5.15.0-83-generic #92-Ubuntu SMP Mon Aug 14 09:30:42 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
- Target = VM (Host Policy)

**To Reproduce**

1. Create and apply this Host policy : 
```yaml
apiVersion: security.kubearmor.com/v1
kind: KubeArmorHostPolicy
metadata:
  name: hsp-block-cron-bash
spec:
  file:
    matchPaths:
    - path: /etc/cron.weekly/man-db
    - path: /home/master/.bash_profile
    matchDirectories:
    - dir: /etc/cron.weekly/
      recursive: true
    - dir: /etc/cron.monthly/
      recursive: true
    - dir: /etc/cron.daily/
      recursive: true
    - dir: /etc/cron.hourly/
      recursive: true
  action:
    Block
```
2. Violate this policy for any directory mentioned ( run 'ls' in /etc/cron.hourly/) 

**Expected behavior**

'ls' should be blocked with permission denied status.

Note: If we create 2 policy with matchPath and matchDirectories separately then it is working as expected.
