### ISSUE TITLE
Add support for all kubearmor command line configurations using KubeArmorConfig CR

### ISSUE THREAD

**Issue by rksharma95** [kubearmor/KubeArmor#1501]
## Feature Request

**Short Description**

Add Support to the KubeArmorConfig to pass all the command line configurations supported by the kubearmor. KubeArmorConfig already support some of the configurations i.e. defaultPosture, defaultVisibility etc. that can be in-effect dynamically. the remaining configurations are mainly pre-install configurations and will require KubeArmor to reboot. Operator is reconciling to watch kubearmor daemonset and can handle any configuration updates.

**Is your feature request related to a problem? Please describe the use case.**

it will enable the user to provide kubearmor configurations using KubeArmorConfig CR.

**Describe the solution you'd like**

```yaml
apiVersion: operator.kubearmor.com/v1
kind: KubeArmorConfig
Spec:
  cluster: "cluster-name"
  host: "host-name"
  grpc: "grpc-port"
  ...
```

**Describe alternatives you've considered**
- feel free to discuss/propose spec design to support the kubearmor configurations.
