### ISSUE TITLE
Host policies auditing syscalls trigger many false positives

### ISSUE THREAD

**Issue by JayJersan** [kubearmor/KubeArmor#1502]
## Feature Request

**Short Description**

Host policies auditing syscalls trigger many false positives as they are auditing the syscalls triggered by the container runtime itself.
This makes it hard to focus on the particular logs of the host.

**To Reproduce**

1. Apply the following policy:
```
apiVersion: security.kubearmor.com/v1
kind: KubeArmorHostPolicy
metadata:
  name: hsp-audit-stig-ubuntu-20-010139-umount
spec:
  nodeSelector:
    matchLabels:
      kubernetes.io/hostname: master-node
  severity: 5 
  tags: ["STIG", "Ubuntu",  "UBTU-20-010139", "audit", "umount"]
  message: "Alert! umount command execution detected" 
  syscalls:
    matchSyscalls:
    - syscall:
      - umount
    action:
      Audit
``` 

2. View `karmor logs`
3. The container runtime triggers a lot of audit events:
```
== Alert / 2023-11-09 05:36:56.854942 ==                                                                                
ClusterName: default                 
HostName: master-node                 
Type: MatchedHostPolicy               
PolicyName: hsp-audit-stig-ubuntu-20-010139-unmount                                                                     
Severity: 5                           
Message: Alert! unmount command execution detected                                                                      
Source: /proc/self/exe init           
Operation: Syscall                    
Data: syscall=SYS_UMOUNT2 target=/run/containerd/runc/k8s.io/b2b8937ea51872962b73ffc3ef08921671f8b7a512d66d43af2290776a0f804a/runc.OohdoG flag=0              
Result: Passed                        
ATags: [STIG Ubuntu UBTU-20-010139 audit unmount]                                                                       
HostPID: 27329                        
HostPPID: 27323                       
PID: 27329                            
ParentProcessName: /var/lib/rancher/k3s/data/24a53467e274f21ca27cec302d5fbd58e7176daf0a47a2c9ce032ee877e0979a/bin/runc  
ProcessName: /var/lib/rancher/k3s/data/24a53467e274f21ca27cec302d5fbd58e7176daf0a47a2c9ce032ee877e0979a/bin/runc        
Tags: STIG,Ubuntu,UBTU-20-010139,audit,unmount                                                                          
``` 

**Expected behavior**

This policy should provide logs for any umount syscall triggered on host without cluttering the logs with those triggered by runc.
