### ISSUE TITLE
Enhance network matching function

### ISSUE THREAD

**Issue by toadzhou** [kubearmor/KubeArmor#1524]
## Enhance the matching function of egress

**short introduction**

Network policies need to add more functionality than just one path to an executable program.

**Add new matching**

```
   network:
     matchProtocols:
     - protocol: tcp, udp
       fromSource:
       - path: /usr/bin/curl
       - fqdn: www.google.com
       - ip: 204.79.197.200/32    #This could be one of my internal proxy gateways
       - port: 443
```

**tetragon related product implementation**
https://tetragon.io/docs/concepts/tracing-policy/selectors/#operator-types

Because of language issues, there may be some problems with expression in some aspects. Comparing similar products, I personally feel that the usage of kubearmro is more in line with my habits, but I still hope to consider strengthening the export restrictions on the network and control the pod exit strategy in a more refined manner. Thanks
