### ISSUE TITLE
Implement RBAC Policy and Service Account for KubeArmor-Relay

### ISSUE THREAD

**Issue by rksharma95** [kubearmor/KubeArmor#1525]
## Feature Request

**Short Description**
`kubearmor-relay` currently operates with an overly permissive RBAC setup, kubearmor servicaccount. potentially creating security risks due to excessive access. To avoid the security risks and ensure a principle of least privilege, we need to add the RBAC policy with appropriate permissions with a dedicated service account for KubeArmor Relay.

**Describe the solution you'd like**

- [x] create a specific RBAC policy and a corresponding service account designed for kubearmor-relay's requirements.
- [x] test the new RBAC policy and service account to confirm functionality
- [x] https://github.com/kubearmor/kubearmor-client/issues/397

**Comment by Utkar5hM** [comment]
I would like to work on this issue.

**Comment by rksharma95** [comment]
hi @Utkar5hM, Thank you for your interest, go ahead and take the lead. let me know if you have any questions.

**Comment by nanu1605** [comment]
Hi @Utkar5hM, Are you working on this issue?

**Comment by Utkar5hM** [comment]
@nanu1605, yes.

**Comment by rootxrishabh** [comment]
@rksharma95  Currently installing through [helm](https://github.com/kubearmor/KubeArmor/tree/main/deployments/helm/KubeArmor) Kubearmor relay uses 
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubearmor-clusterrole
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - nodes
  - namespaces
  - configmaps
  verbs:
  - get
  - patch
  - list
  - watch
  - update
- apiGroups:
  - apps
  resources:
  - deployments
  - replicasets
  - daemonsets
  - statefulsets
  verbs:
  - get
  - patch
  - list
  - watch
  - update
- apiGroups:
  - security.kubearmor.com
  resources:
  - kubearmorpolicies
  - kubearmorhostpolicies
  verbs:
  - get
  - list
  - watch
  - update
  - delete
- nonResourceURLs:
  - /apis
  - /apis/*
  verbs:
  - get
```
What cluster roles are we looking to have for the kubearmor relay service account?
