### ISSUE TITLE
Operator - doesn't respect version defined in CRD

### ISSUE THREAD

**Issue by michalschott** [kubearmor/KubeArmor#1564]
## Bug Report

I’m facing nasty issue, where kubearmor-operator tries (I believe, since I have a webhook preventing using latest tag) to constantly upgrade kubearmor-controller. My CRD:

```
apiVersion: operator.kubearmor.com/v1
kind: KubeArmorConfig
metadata:
    name: kubearmor
    namespace: kubearmor
spec:
    kubearmorControllerImage:
        image: kubearmor/kubearmor-controller:v1.1.1
```

But I can observe this in logs:

```
kubearmor-operator-598bd799bd-g48x2 kubearmor-operator {"level":"warn","ts":1703774002.8609407,"caller":"controller/resources.go:382","msg":"Cannot update deployment kubearmor-controller, error=admission webhook \"polaris.fairwinds.com\" denied the request: \nPolaris prevented this deployment due to configuration problems:\n- Container manager: Image tag should be specified\n"}
```

Would be great to have an ability to disable this behaviour. Especially in environments where you sync images to your own repo to bypass dockerhub limitations :wink:

https://kubearmor.slack.com/archives/C01F9V3SEHY/p1703774349019029

**Expected behavior**

Version in CRD should be respected.
