### ISSUE TITLE
Helm chart is missing RBAC rules / Operator doesn't create RBAC rules

### ISSUE THREAD

**Issue by michalschott** [kubearmor/KubeArmor#1565]
## Bug Report

Helm chart / controller doesn't create RBAC rules:

```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubearmor-snitch-clusterrole
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubearmor-snitch-clusterrole-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubearmor-snitch-clusterrole
subjects:
- kind: ServiceAccount
  name: kubearmor-snitch
  namespace: kubearmor
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubearmor-controller-clusterrole
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - list
  - watch
- apiGroups:
  - security.kubearmor.com
  resources:
  - kubearmorhostpolicies
  - kubearmorpolicies
  verbs:
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubearmor-controller-clusterrole-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubearmor-controller-clusterrole
subjects:
- kind: ServiceAccount
  name: kubearmor-controller
  namespace: kubearmor
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubearmor-bpf-containerd-clusterrole
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - namespaces
  - nodes
  verbs:
  - list
  - watch
- apiGroups:
  - security.kubearmor.com
  resources:
  - kubearmorpolicies
  verbs:
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubearmor-bpf-containerd-clusterrole-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubearmor-bpf-containerd-clusterrole
subjects:
- kind: ServiceAccount
  name: kubearmor
  namespace: kubearmor
```

**Expected behavior**

RBAC as other objects should be created.
