### ISSUE TITLE
Single policy to block everything expect few source

### ISSUE THREAD

**Issue by janavenkat** [kubearmor/KubeArmor#1607]
### Discussed in https://github.com/kubearmor/KubeArmor/discussions/1588

<div type='discussions-op-text'>

<sup>Originally posted by **janavenkat** January 19, 2024</sup>
We're trying to understand the policy for the containers.

We have already read about security policy
https://docs.kubearmor.io/kubearmor/documentation/security_policy_specification

What we want to achieve is to block file access to /run/secrets directory expect from the php process, currently we have to define two policies. If we do this blacklist mode is enabled because of the allow action, this means we have to specify the all of the other path in the container.

1. Allow PHP process to access the dir
```yaml
apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: aws-creds-allow-php
  namespace: test
spec:
  selector:
    matchLabels:
      repository: test
  file:
    matchDirectories:
      - dir: /run/secrets/
        fromSource:
          - path: /usr/local/bin/php
  action:
    Allow.  ==> This fallback to defaultPosture
```

2. Block all process to access the dir
```yaml
apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: aws-creds-block
  namespace: test
spec:
  selector:
    matchLabels:
      repository: test
  file:
    matchDirectories:
      - dir: /run/secrets/
  action:
    Block
```

Is there a way to achieve this without the blacklist mode behaviour? 

</div>

**Comment by daemon1024** [comment]
> What we want to achieve is to block file access to /run/secrets directory expect from the php process, currently we have to define two policies. If we do this blacklist mode is enabled because of the allow action, this means we have to specify the all of the other path in the container.

You are right about two policies, but you can keep the two rules as part of the same policy.
And regarding the concern about specifying all other paths in container

https://github.com/kubearmor/KubeArmor/discussions/1588#discussioncomment-8184102

As I mentioned in the Github Discussions as well, you can just choose to mention allow everything from root and paths outside of /run/secrets won't be affected

If something is not clear, Feel free to join us on our [Slack](https://join.slack.com/t/kubearmor/shared_invite/zt-2bhlgoxw1-WTLMm_ica8PIhhNBNr2GfA)
[![Slack](https://img.shields.io/badge/Join%20Our%20Community-Slack-blue)](https://join.slack.com/t/kubearmor/shared_invite/zt-2bhlgoxw1-WTLMm_ica8PIhhNBNr2GfA)

We can sync up on a call if needed so that we can better tailor what you want to achieve.

**Comment by daemon1024** [comment]
Marking this as resolved with the following YAML
```yaml
apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: aws-creds-allow-php
  namespace: test
spec:
  selector:
    matchLabels:
      repository: test
  file:
    matchDirectories:
      - dir: /run/secrets/
        recursive: true
        action: Block
      - dir: / # You do not need to add individual paths, you can allow everything from root
        recursive: true
      - dir: /run/secrets/
        recursive: true
        fromSource:
          - path: /usr/local/bin/php
  action:
    Allow
```
