### ISSUE TITLE
Enhancement: Support new pod API for AppArmor profiles with Kubernetes 1.30+

### ISSUE THREAD

**Issue by DelusionalOptimist** [kubearmor/KubeArmor#1673]
## Feature Request

**Description**
KubeArmor supports using AppArmor as an enforcer for protecting Kubernetes pods and nodes.
For pods/pod templates, this is done by adding the annotation `container.apparmor.security.beta.kubernetes.io/<container_name>: <profile_ref>` till now. 

However, AppArmor support is [moving to GA](https://github.com/kubernetes/enhancements/pull/4417) 🥳 in the upcoming Kubernetes v1.30 release and the annotation would be soon removed in accordance to K8s' deprecation policy. 

**Describe the solution you'd like**
Once K8s 1.30 is released, support both the new `AppArmorProfile` field that's being added at pod and container level `securityContext`, along with the old annotation based mechanism for backward compatibility.

**References**
- AppArmor Support KEP: https://github.com/kubernetes/enhancements/blob/master/keps/sig-node/24-apparmor/

**Comment by DelusionalOptimist** [comment]
Thanks for showing interest @yp969803, do share how you plan to go about and feel free to ask any questions. : )

**Comment by yp969803** [comment]
```
apiVersion: v1
kind: Pod
metadata:
  name: example-pod
spec:
  containers:
   - name: example-container
    image: nginx
    securityContext:
      appArmorProfile: "localhost/example-apparmor-profile"

  ```
