### ISSUE TITLE
There is still no /usr/src dir

### ISSUE THREAD

**Issue by aberfeldy** [kubearmor/KubeArmor#1710]
## Bug Report
following up on  #1265: sorry for the long delay. Switched from Flatcar to buildroot and it took some time.
I tried out the new operator setup and so far I like the setup process, nice improvement. Unfortunately I still can't get it to run with the default settings. It detects our crio environment just fine, but the bpf-crio pods want to host-mount the `/usr/src` directory.
This directory still doesn't exist and we don't want to build it in an OS-Release just so that KubeArmor can start properly. 
Is there a possibility to make it either optional via helm-values or disable it by detection (as crio/docker is detected)? 

**General Information**

- Environment description: k3s with crio
- Kernel version: 6.6.16
- Orchestration system version in use: v1.28.5+k3s1

**To Reproduce**

- take a OS without `/usr/src` (e.g flatcar, buildroot)
- install Kubearmor operator
- bpf pods can't start

**Expected behavior**

Ignoring `/usr/src` if not existing. If it's not there, no need to monitor it

**Screenshots**

![Screenshot 2024-04-02 at 10 56 25](https://github.com/kubearmor/KubeArmor/assets/1640534/0d6bdc01-0f6f-4ebf-82f5-e6f9d0ede518)

**Comment by daemon1024** [comment]
As per my understanding, The operator wouldn't try to mount `/usr/src` unless there's no BTF present. 

Kernel version is very recent so I am not sure why would BTF be not present.
Can you share annotations added to nodes? (`kubectl describe nodes`)

// @rksharma95

**Comment by aberfeldy** [comment]
Sure thing. those are all the annotations nodes have.  
```yaml
alpha.kubernetes.io/provided-node-ip: x.x.x.x
csi.volume.kubernetes.io/nodeid: {"rook-ceph.cephfs.csi.ceph.com":"nodename","rook-ceph.rbd.csi.ceph.com":"nodename"}
k3s.io/node-args: ["server","--server","https://cp-lb:443","--token","********","--node-ip","x.x.x.x","--node-external-ip","x.x.x.x","--...
k3s.io/node-config-hash: ...
k3s.io/node-env: {"K3S_DATA_DIR":"/var/lib/rancher/k3s/data/28f7e87eba734b7f7731dc900e2c84e0e98ce869f3dcf57f65dc7bbb80e12e56"}
kubevirt.io/heartbeat: 2024-04-02T14:29:31Z
kubevirt.io/ksm-handler-managed: false
node.alpha.kubernetes.io/ttl: 0
volumes.kubernetes.io/controller-managed-attach-detach: true
```

**Comment by rksharma95** [comment]
@aberfeldy can you please share node labels?

**Comment by aberfeldy** [comment]
sure:
```yaml
beta.kubernetes.io/arch: amd64
beta.kubernetes.io/os: linux
cpu-feature.node.kubevirt.io/3dnowprefetch: true
cpu-feature.node.kubevirt.io/abm: true
cpu-feature.node.kubevirt.io/adx: true
cpu-feature.node.kubevirt.io/aes: true
cpu-feature.node.kubevirt.io/amd-ssbd: true
cpu-feature.node.kubevirt.io/amd-stibp: true
cpu-feature.node.kubevirt.io/apic: true
cpu-feature.node.kubevirt.io/arat: true
cpu-feature.node.kubevirt.io/arch-capabilities: true
cpu-feature.node.kubevirt.io/avx: true
cpu-feature.node.kubevirt.io/avx2: true
cpu-feature.node.kubevirt.io/bmi1: true
cpu-feature.node.kubevirt.io/bmi2: true
cpu-feature.node.kubevirt.io/clflush: true
cpu-feature.node.kubevirt.io/clflushopt: true
cpu-feature.node.kubevirt.io/clwb: true
cpu-feature.node.kubevirt.io/clzero: true
cpu-feature.node.kubevirt.io/cmov: true
cpu-feature.node.kubevirt.io/cmp_legacy: true
cpu-feature.node.kubevirt.io/cr8legacy: true
cpu-feature.node.kubevirt.io/cx16: true
cpu-feature.node.kubevirt.io/cx8: true
cpu-feature.node.kubevirt.io/de: true
cpu-feature.node.kubevirt.io/f16c: true
cpu-feature.node.kubevirt.io/fma: true
cpu-feature.node.kubevirt.io/fpu: true
cpu-feature.node.kubevirt.io/fsgsbase: true
cpu-feature.node.kubevirt.io/fxsr: true
cpu-feature.node.kubevirt.io/fxsr_opt: true
cpu-feature.node.kubevirt.io/hypervisor: true
cpu-feature.node.kubevirt.io/ibpb: true
cpu-feature.node.kubevirt.io/ibrs: true
cpu-feature.node.kubevirt.io/invtsc: true
cpu-feature.node.kubevirt.io/lahf_lm: true
cpu-feature.node.kubevirt.io/lbrv: true
cpu-feature.node.kubevirt.io/lfence-always-serializing: true
cpu-feature.node.kubevirt.io/lm: true
cpu-feature.node.kubevirt.io/mca: true
cpu-feature.node.kubevirt.io/mce: true
cpu-feature.node.kubevirt.io/mds-no: true
cpu-feature.node.kubevirt.io/misalignsse: true
cpu-feature.node.kubevirt.io/mmx: true
cpu-feature.node.kubevirt.io/mmxext: true
cpu-feature.node.kubevirt.io/movbe: true
cpu-feature.node.kubevirt.io/msr: true
cpu-feature.node.kubevirt.io/mtrr: true
cpu-feature.node.kubevirt.io/npt: true
cpu-feature.node.kubevirt.io/nrip-save: true
cpu-feature.node.kubevirt.io/null-sel-clr-base: true
cpu-feature.node.kubevirt.io/nx: true
cpu-feature.node.kubevirt.io/osvw: true
cpu-feature.node.kubevirt.io/pae: true
cpu-feature.node.kubevirt.io/pat: true
cpu-feature.node.kubevirt.io/pause-filter: true
cpu-feature.node.kubevirt.io/pclmuldq: true
cpu-feature.node.kubevirt.io/pdpe1gb: true
cpu-feature.node.kubevirt.io/perfctr_core: true
cpu-feature.node.kubevirt.io/pfthreshold: true
cpu-feature.node.kubevirt.io/pge: true
cpu-feature.node.kubevirt.io/pni: true
cpu-feature.node.kubevirt.io/popcnt: true
cpu-feature.node.kubevirt.io/pschange-mc-no: true
cpu-feature.node.kubevirt.io/pse: true
cpu-feature.node.kubevirt.io/pse36: true
cpu-feature.node.kubevirt.io/rdctl-no: true
cpu-feature.node.kubevirt.io/rdpid: true
cpu-feature.node.kubevirt.io/rdrand: true
cpu-feature.node.kubevirt.io/rdseed: true
cpu-feature.node.kubevirt.io/rdtscp: true
cpu-feature.node.kubevirt.io/sep: true
cpu-feature.node.kubevirt.io/sha-ni: true
cpu-feature.node.kubevirt.io/skip-l1dfl-vmentry: true
cpu-feature.node.kubevirt.io/smap: true
cpu-feature.node.kubevirt.io/smep: true
cpu-feature.node.kubevirt.io/spec-ctrl: true
cpu-feature.node.kubevirt.io/ssbd: true
cpu-feature.node.kubevirt.io/sse: true
cpu-feature.node.kubevirt.io/sse2: true
cpu-feature.node.kubevirt.io/sse4.1: true
cpu-feature.node.kubevirt.io/sse4.2: true
cpu-feature.node.kubevirt.io/sse4a: true
cpu-feature.node.kubevirt.io/ssse3: true
cpu-feature.node.kubevirt.io/stibp: true
cpu-feature.node.kubevirt.io/svm: true
cpu-feature.node.kubevirt.io/svme-addr-chk: true
cpu-feature.node.kubevirt.io/syscall: true
cpu-feature.node.kubevirt.io/tsc: true
cpu-feature.node.kubevirt.io/tsc-deadline: true
cpu-feature.node.kubevirt.io/tsc-scale: true
cpu-feature.node.kubevirt.io/tsc_adjust: true
cpu-feature.node.kubevirt.io/umip: true
cpu-feature.node.kubevirt.io/v-vmsave-vmload: true
cpu-feature.node.kubevirt.io/vgif: true
cpu-feature.node.kubevirt.io/virt-ssbd: true
cpu-feature.node.kubevirt.io/vmcb-clean: true
cpu-feature.node.kubevirt.io/vme: true
cpu-feature.node.kubevirt.io/wbnoinvd: true
cpu-feature.node.kubevirt.io/x2apic: true
cpu-feature.node.kubevirt.io/xgetbv1: true
cpu-feature.node.kubevirt.io/xsave: true
cpu-feature.node.kubevirt.io/xsavec: true
cpu-feature.node.kubevirt.io/xsaveerptr: true
cpu-feature.node.kubevirt.io/xsaveopt: true
cpu-model-migration.node.kubevirt.io/EPYC-Rome: true
cpu-model-migration.node.kubevirt.io/Nehalem: true
cpu-model-migration.node.kubevirt.io/Nehalem-IBRS: true
cpu-model-migration.node.kubevirt.io/Opteron_G1: true
cpu-model-migration.node.kubevirt.io/Opteron_G2: true
cpu-model-migration.node.kubevirt.io/Penryn: true
cpu-model-migration.node.kubevirt.io/SandyBridge: true
cpu-model-migration.node.kubevirt.io/SandyBridge-IBRS: true
cpu-model-migration.node.kubevirt.io/Westmere: true
cpu-model-migration.node.kubevirt.io/Westmere-IBRS: true
cpu-model.node.kubevirt.io/Nehalem: true
cpu-model.node.kubevirt.io/Nehalem-IBRS: true
cpu-model.node.kubevirt.io/Opteron_G1: true
cpu-model.node.kubevirt.io/Opteron_G2: true
cpu-model.node.kubevirt.io/Penryn: true
cpu-model.node.kubevirt.io/SandyBridge: true
cpu-model.node.kubevirt.io/SandyBridge-IBRS: true
cpu-model.node.kubevirt.io/Westmere: true
cpu-model.node.kubevirt.io/Westmere-IBRS: true
cpu-timer.node.kubevirt.io/tsc-frequency: 2495312000
cpu-timer.node.kubevirt.io/tsc-scalable: true
cpu-vendor.node.kubevirt.io/AMD: true
cpumanager: false
host-model-cpu.node.kubevirt.io/EPYC-Rome: true
host-model-required-features.node.kubevirt.io/amd-ssbd: true
host-model-required-features.node.kubevirt.io/arch-capabilities: true
host-model-required-features.node.kubevirt.io/cmp_legacy: true
host-model-required-features.node.kubevirt.io/hypervisor: true
host-model-required-features.node.kubevirt.io/ibrs: true
host-model-required-features.node.kubevirt.io/invtsc: true
host-model-required-features.node.kubevirt.io/lbrv: true
host-model-required-features.node.kubevirt.io/lfence-always-serializing: true
host-model-required-features.node.kubevirt.io/mds-no: true
host-model-required-features.node.kubevirt.io/null-sel-clr-base: true
host-model-required-features.node.kubevirt.io/pause-filter: true
host-model-required-features.node.kubevirt.io/pfthreshold: true
host-model-required-features.node.kubevirt.io/pschange-mc-no: true
host-model-required-features.node.kubevirt.io/rdctl-no: true
host-model-required-features.node.kubevirt.io/skip-l1dfl-vmentry: true
host-model-required-features.node.kubevirt.io/spec-ctrl: true
host-model-required-features.node.kubevirt.io/ssbd: true
host-model-required-features.node.kubevirt.io/stibp: true
host-model-required-features.node.kubevirt.io/svme-addr-chk: true
host-model-required-features.node.kubevirt.io/tsc-deadline: true
host-model-required-features.node.kubevirt.io/tsc-scale: true
host-model-required-features.node.kubevirt.io/tsc_adjust: true
host-model-required-features.node.kubevirt.io/v-vmsave-vmload: true
host-model-required-features.node.kubevirt.io/vgif: true
host-model-required-features.node.kubevirt.io/virt-ssbd: true
host-model-required-features.node.kubevirt.io/vmcb-clean: true
host-model-required-features.node.kubevirt.io/x2apic: true
hyperv.node.kubevirt.io/base: true
hyperv.node.kubevirt.io/frequencies: true
hyperv.node.kubevirt.io/ipi: true
hyperv.node.kubevirt.io/reenlightenment: true
hyperv.node.kubevirt.io/reset: true
hyperv.node.kubevirt.io/runtime: true
hyperv.node.kubevirt.io/synic: true
hyperv.node.kubevirt.io/synic2: true
hyperv.node.kubevirt.io/synictimer: true
hyperv.node.kubevirt.io/time: true
hyperv.node.kubevirt.io/tlbflush: true
hyperv.node.kubevirt.io/vpindex: true
instance.hetzner.cloud/is-root-server: true
k8slens-edit-resource-version: v1
kubearmor.io/apparmorfs: no
kubearmor.io/btf: no
kubearmor.io/enforcer: bpf
kubearmor.io/rand: 7s7j
kubearmor.io/runtime: cri-o
kubearmor.io/seccomp: yes
kubearmor.io/securityfs: yes
kubearmor.io/socket: var_run_crio_crio.sock
kubernetes.io/arch: amd64
kubernetes.io/hostname: NODENAME
kubernetes.io/os: linux
kubevirt.io/ksm-enabled: false
kubevirt.io/schedulable: true
kubevirt.io/sev: 
node-access: protected
node-role.kubernetes.io/control-plane: true
node-role.kubernetes.io/master: true
scheduling.node.kubevirt.io/tsc-frequency-2495310000: true
scheduling.node.kubevirt.io/tsc-frequency-2495312000: true
topology.kubernetes.io/region: REGION
topology.rook.io/datacenter: DC
topology.rook.io/rack: RACK
```
