### ISSUE TITLE
the "/usr/bin/sleep 1" example policy does not work when installation on a ubuntu22.04.4 VM using systemd mode

### ISSUE THREAD

**Issue by seamaner** [kubearmor/KubeArmor#1725]
## Bug Report

**General Information**
the "/usr/bin/sleep 1" example policy does not work when installation on a ubuntu VM using systemd mode:
install:   
`apt install ./kubearmor_1.3.2_linux-amd64.deb`
karmor probe:
```
Found KubeArmor running in Systemd mode

Host :
        OS Image:                       Ubuntu 22.04.4 LTS
        Kernel Version:                 5.15.0-102-generic
        Kubelet Version:
        Container Runtime:
        Active LSM:                     BPFLSM
        Host Security:                  true
        Container Security:             true
        Container Default Posture:      audit(File)                             audit(Capabilities)      audit(Network)
        Host Default Posture:           audit(File)                             audit(Capabilities)      audit(Network)
        Host Visibility:                process,file,network,capabilities
Host Policies :
+------------+-----------------------------------+
| HOST NAME  |              POLICY               |
+------------+-----------------------------------+
| ubuntu     | hsp-kubearmor-dev-proc-path-block |
+------------+-----------------------------------+
Armored Up Containers :
+----------------+--------+
| CONTAINER NAME | POLICY |
+----------------+--------+
+----------------+--------+
```
- Environment description (GKE, VM-Kubeadm, vagrant-dev-env, minikube, microk8s, ...)
it is a ubuntu host
- Kernel version (run `uname -a`)  
`Linux ubuntu 5.15.0-102-generic #112-Ubuntu SMP Tue Mar 5 16:50:32 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux`
- Orchestration system version in use (e.g. `kubectl version`, ...)
no k8s, deb installation on a VM 
- Link to relevant artifacts (policies, deployments scripts, ...)
karmor vm policy add hostpolicy.yaml
hostpolicy.yaml:   
```
apiVersion: security.kubearmor.com/v1
kind: KubeArmorHostPolicy
metadata:
  name: hsp-kubearmor-dev-proc-path-block
spec:
  process:
    matchPaths:
    - path: /usr/bin/sleep # try sleep 1
    - path: /usr/bin/top # try sleep 1
  action:
    Block
```     
 

- Target containers/pods

**To Reproduce**

1. Instruction 1
3. Instruction 2
/usr/bin/sleep 1
**Expected behavior**
the sleep path is correct: `/usr/bin/sleep`. And do the test `/usr/bin/sleep 1` in another new terminal. 
It executes successfully, and no `permission deny` output.

**Screenshots**

**Comment by DelusionalOptimist** [comment]
Hey @seamaner. Apologies for getting to this late.
In the host policy that you've shared, can you add a `nodeSelector`?

Something like below. You can get the name-of-your-host by running `hostname`.
```yaml
apiVersion: security.kubearmor.com/v1
kind: KubeArmorHostPolicy
metadata:
  name: hsp-kubearmor-dev-proc-path-block
spec:
  nodeSelector:
    matchLabels:
      kubearmor.io/hostname: name-of-your-host
  process:
    matchPaths:
    - path: /usr/bin/sleep # try sleep 1
    - path: /usr/bin/top # try sleep 1
  action:
    Block
```

The above wasn't a required field earlier but it has been changed in the recent versions. We are lacking behind in the documentation on this one. :sweat_smile: 

On the brighter side, we now have regex based matching in the above label, so to have the same effect in which a policy will be applied to all nodes regardless of selector, you can do something like:
```yaml
  nodeSelector:
    matchLabels:
      kubearmor.io/hostname: "*"
```

Please try it out and let us know if this doesn't fix it. Thanks! : )

**Comment by seamaner** [comment]
thanks for your reply. This doesn't fix it after adding "nodeSelector".

**Comment by DelusionalOptimist** [comment]
That's sad. Can you share the logs from `kubearmor.service`, when you apply a policy? Also the policy in place?

Just to confirm nodeSelector is `kubearmor.io/hostname: ubuntu`, based on your node's name and after editing the policy you reapply with `karmor vm policy add <path-to-policy>`, right?

**Comment by seamaner** [comment]
> That's sad. Can you share the logs from `kubearmor.service`, when you apply a policy? Also the policy in place?
> 
> Just to confirm nodeSelector is `kubearmor.io/hostname: ubuntu`, based on your node's name and after editing the policy you reapply with `karmor vm policy add <path-to-policy>`, right?
journalctl -u kubearmor.service latest logs:
```
journalctl -u kubearmor.service
......
May 11 04:17:13 ubuntu kubearmor[1137]: 2024-05-11 04:17:13.247703        INFO        Added a new client (150cbdb8-c57c-4f92-9265-eee92c332000, policy) for WatchAlerts
May 11 04:17:21 ubuntu kubearmor[1137]: 2024-05-11 04:17:21.610467        INFO        Deleted the client (150cbdb8-c57c-4f92-9265-eee92c332000) for WatchAlerts
May 11 04:20:24 ubuntu kubearmor[1137]: 2024-05-11 04:20:24.494330        INFO        Detected a Host Security Policy (modified/hsp-kubearmor-dev-proc-path-block)
May 11 04:20:24 ubuntu kubearmor[1137]: 2024-05-11 04:20:24.496353        INFO        Updating host rules
May 11 04:20:24 ubuntu kubearmor[1137]: 2024-05-11 04:20:24.496417        INFO        Deleting inner map for host

```

the host name is set as * , like this:
```
 cat hostpolicy.yaml
apiVersion: security.kubearmor.com/v1
kind: KubeArmorHostPolicy
metadata:
  name: hsp-kubearmor-dev-proc-path-block
spec:
  nodeSelector:
    matchLables:
      kubearmor.io/hostname: "*"
  process:
    matchPaths:
    - path: /usr/bin/sleep # try sleep 1
    - path: /usr/bin/top # try sleep 1
  action:
    Block
ubuntu@ubuntu:~$ karmor vm policy add hostpolicy.yaml
Policy Modified
````
i alse test hostname "ubuntu" as my hostname is "ubuntu".

**Comment by DelusionalOptimist** [comment]
@seamaner Can you change from `matchLables` to `matchLabels`? 😅

**Comment by seamaner** [comment]
> @seamaner Can you change from `matchLables` to `matchLabels`? 😅

my mistake. Thank you very much for your help.  
this works:  
```
cat hostpolicy.yaml
apiVersion: security.kubearmor.com/v1
kind: KubeArmorHostPolicy
metadata:
  name: hsp-kubearmor-dev-proc-path-block
spec:
  nodeSelector:
    matchLabels:
      kubearmor.io/hostname: "ubuntu"
  process:
    matchPaths:
    - path: /usr/bin/sleep # try sleep 1
    - path: /usr/bin/top # try sleep 1
  action:
    Block
```
Other infomation:   
if hostname is set to *:  `kubearmor.io/hostname: "*"`, it will not work.
