### ISSUE TITLE
Refactor KubeArmor Operator

### ISSUE THREAD

**Issue by rksharma95** [kubearmor/KubeArmor#1779]
## Refactor KubeArmor Operator

- refactor kubearmorConfig keep it close to k8s manifest spec

  Current:
  ```
  kubearmorImage:
    image:
    imagePullPolicy
  ...  

  ```
  Proposed:
  ```
  kubearmor:
    image:
    args:

  kubearmorRelay:
    image:
    args:

  kubearmorController:
  ...
  ```

- avoid snitch's [dependency for serviceaccount](https://github.com/kubearmor/KubeArmor/blob/main/pkg/KubeArmorOperator/internal/controller/resources.go#L435) being created after KubeArmorConfig CR has been created, to avoid increasing time delay due to reconcilation.
- avoid [seperate resource update](https://github.com/kubearmor/KubeArmor/blob/52352c80f576f3905bceb83a1fa4197444c34529/pkg/KubeArmorOperator/internal/controller/cluster.go#L278-L282) for each configuration update 
- optimize [cert roatation logic](https://github.com/kubearmor/KubeArmor/blob/52352c80f576f3905bceb83a1fa4197444c34529/pkg/KubeArmorOperator/internal/controller/resources.go#L714)
- discuss to decide if [tight loop](https://github.com/kubearmor/KubeArmor/blob/52352c80f576f3905bceb83a1fa4197444c34529/pkg/KubeArmorOperator/internal/controller/resources.go#L427) should be replaced with informer based reconcider. reconciler will require watch permission for managing k8s resources.

**Comment by carlosrodfern** [comment]
The change to the operator CRD is also desirable to be able to set the log level in the `values.yaml` in the helm chart for the controller: https://github.com/kubearmor/KubeArmor/pull/1849

**Comment by carlosrodfern** [comment]
More details for the Proposal:

```
kubearmor:
  image:
     repository: ?
     tag: ?
     pullPolicy: ?
  args: []
  resources:
    limits:
      cpu: ?
      memory: ?
    requests:
      cpu: ?
      memory: ?

kubearmorRelay:
  image:
     repository: ?
     tag: ?
     pullPolicy: ?
  args: []
  resources:
    limits:
      cpu: ?
      memory: ?
    requests:
      cpu: ?
      memory: ?

kubearmorController:
  image:
     repository: ?
     tag: ?
     pullPolicy: ?
  args: []
  resources:
    limits:
      cpu: ?
      memory: ?
    requests:
      cpu: ?
      memory: ?
```

Perhaps even a global too?
```
global:
  image:
    pullPolicy: ?
    repository: ?
```

This is inspired on the typical pattern seen in helm values.
