### ISSUE TITLE
Increase granularity on the selectors to target a specific container within a pod

### ISSUE THREAD

**Issue by carlosrodfern** [kubearmor/KubeArmor#1832]
## Feature Request

**Short Description**

Have the ability to target one container in a multicontainer pod when defining a policy.

**Is your feature request related to a problem? Please describe the use case.**

For example, when the developer sets up sidecars for secret management (vault). In that case, the developers want the vault container within the pod to access the kubernetes token, however, the other container just accessing the secrets shouldn't have access to the token.

In general, each container within one pod could need different policies.

**Describe the solution you'd like**

Somehow, being able to specify the actual container in the selector, not just the pod.

**Describe alternatives you've considered**

I'm writing this because I don't see a way to do it in the documentation, but I'm open to any solution or design technique that can be used to achieve this.

**Comment by carlosrodfern** [comment]
Hmm, it looks like, at least in `containerd`, the handler adds `kubearmor.io/container.name` to the list of labels of a specific container:

https://github.com/kubearmor/KubeArmor/blob/6cd782f39ab4280312ecdfd9f228df638aee593c/KubeArmor/core/containerdHandler.go#L229

So, in theory, I should be able to use that label in the selector. I'm having a hard time finding that label in the documentation, though.

**Comment by carlosrodfern** [comment]
Well, that didn't work for whatever reason.

```yaml
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: debug-pod
  name: debug-pod
  namespace: application
spec:
  containers:
    - command: ["/bin/bash", "-c", "trap : TERM INT; sleep infinity & wait"]
      image: docker.io/redhat/ubi8:latest
      imagePullPolicy: Always
      name: rhel8
    - command: ["/bin/bash", "-c", "trap : TERM INT; sleep infinity & wait"]
      image: docker.io/redhat/ubi9:latest
      imagePullPolicy: Always
      name: rhel9
---
apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: debug-pod-dnf-block
  namespace: application
spec:
  selector:
    matchLabels:
      run: debug-pod
      kubearmor.io/container.name: rhel8
  process:
    matchPaths:
    - path: /usr/bin/dnf
  action:
    Block
```



```
$ kubectl -n application exec -it debug-pod -c rhel9 -- /usr/bin/dnf --version
4.14.0
  Installed: dnf-0:4.14.0-9.el9.noarch at Thu Jul 18 15:50:10 2024
  Built    : Red Hat, Inc. <http://bugzilla.redhat.com/bugzilla> at Thu Oct 26 05:20:14 2023

  Installed: rpm-0:4.16.1.3-29.el9.x86_64 at Thu Jul 18 15:50:08 2024
  Built    : Red Hat, Inc. <http://bugzilla.redhat.com/bugzilla> at Wed Dec 13 11:41:48 2023

$ kubectl -n application exec -it debug-pod -c rhel8 -- /usr/bin/dnf --version
4.7.0
  Installed: dnf-0:4.7.0-20.el8.noarch at Thu Jun 27 11:16:27 2024
  Built    : Red Hat, Inc. <http://bugzilla.redhat.com/bugzilla> at Mon Oct 16 13:53:08 2023

  Installed: rpm-0:4.14.3-31.el8.x86_64 at Thu Jun 27 11:16:26 2024
  Built    : Red Hat, Inc. <http://bugzilla.redhat.com/bugzilla> at Wed Dec 13 13:45:49 2023
```


The audit logs for rhel8.
```
karmor logs --logFilter=all -n application | grep debug
local port to be used for port forwarding kubearmor-relay-*****
Created a gRPC client (localhost:****)
Checked the liveness of the gRPC server
Started to watch alerts
Started to watch logs
PodName: debug-pod
Labels: run=debug-pod
Owner: map[Name:debug-pod Namespace:application Ref:Pod]
PodName: debug-pod
Labels: run=debug-pod
Owner: map[Name:debug-pod Namespace:application Ref:Pod]
PodName: debug-pod
Labels: run=debug-pod
Owner: map[Name:debug-pod Namespace:application Ref:Pod]
PodName: debug-pod
Labels: run=debug-pod
Owner: map[Name:debug-pod Namespace:application Ref:Pod]
PodName: debug-pod
Labels: run=debug-pod
Owner: map[Name:debug-pod Namespace:application Ref:Pod]
PodName: debug-pod
Labels: run=debug-pod
Owner: map[Name:debug-pod Namespace:application Ref:Pod]
PodName: debug-pod
Labels: run=debug-pod
Owner: map[Name:debug-pod Namespace:application Ref:Pod]
```

So, it appears that the kubearmor label is not being used in this AWS EKS scenario, which appears to be because of the condition `if !cfg.GlobalCfg.K8sEnv` right before.

**Comment by carlosrodfern** [comment]
I found a test case for k8s env here: https://github.com/kubearmor/KubeArmor/blob/main/tests/k8s_env/multicontainer/manifests/container-1-ls-block.yaml

That test case, does use the `kubearmor.io/container.name` with an array expression. I also tried `[rhel8]` but not luck.

The logs appear to indicate that the `kubearmor.io/container.name` label is not present (perhaps because it is a k8s env with `containerd`?):
```
PodName: debug-pod
Labels: run=debug-pod
```

Anyway, it does appear to be a way to do this with the `kubearmor.io/container.name` label, but it seems that it needs some clarification.

**Comment by carlosrodfern** [comment]
I got it to work with `file`.

```
kind: KubeArmorPolicy
metadata:
  name: debug-pod-dnf-block
  namespace: application
spec:
  selector:
    matchLabels:
      run: debug-pod
      kubearmor.io/container.name: "[rhel8]"
  file:
    matchDirectories:
    - dir: /etc/
      readOnly: true
      recursive: true
  action:
    Block
```

```
$ kubectl -n application exec -it debug-pod -c rhel8 -- /usr/bin/touch /etc/test.conf
touch: cannot touch '/etc/test.conf': Permission denied
command terminated with exit code 1

$ kubectl -n application exec -it debug-pod -c rhel9 -- /usr/bin/touch /etc/test.conf
# success here
```

So, the `kubearmor.io/container.name` label is how to achieve the granularity.

The fact that it is not working for `process` seems to be another issue related to KubeArmor and the AL2 machines in AWS EKS.

I'll close this issue since this feature is already in place.
