### ISSUE TITLE
KubeArmor is not blocking the process as expected

### ISSUE THREAD

**Issue by myugan** [kubearmor/KubeArmor#1839]
## Bug Report

**General Information**

- Environment description (GKE, VM-Kubeadm, vagrant-dev-env, minikube, microk8s, ...): `kubeadm`
- Kernel version (run `uname -a`): `6.5.0-1020-aws`
- Orchestration system version in use (e.g. `kubectl version`, ...): v1.29.5
- Link to relevant artifacts (policies, deployments scripts, ...)
- Target containers/pods

**To Reproduce**

1. Install KubeArmor using the Helm chart
2. Apply the policy below to block the `sleep` command. Verify that the policy is successfully applied to the respective pod using `karmor probe`.

```
cat > ksp-ubuntu-proc-block.yaml <<EOL
apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-ubuntu-proc-block
  namespace: default
spec:
  message: "block /usr/bin/sleep"
  selector:
    matchLabels:
      os: ubuntu
  process:
    matchPaths:
    - path: /usr/bin/sleep
  action:
    Block
EOL
```

**Expected behavior**

KubeArmor must block any activities according to the created policy.

**Screenshots**

<img width="1324" alt="image" src="https://github.com/user-attachments/assets/8bed5082-67a5-4224-a880-a2b81a0c0c86">

**Comment by daemon1024** [comment]
Hey @myugan, Can you share how are trying to violate it and what's the output you see?
The configuration looks good to me.

Additionally can you run `which sleep` in the ubuntu pod and check what's the binary name?

**Comment by myugan** [comment]
Hello @daemon1024, I have verified that the binary of sleep appears to be correct, and I even attempted to replace it with another binary file, but it did not block either. Is there a method to display the complete debug message in order to understand why it is not blocking the action according to the policy? Additionally, the output is not appearing in the `karmor logs`

**Comment by daemon1024** [comment]
Can we check if the Pod has apparmor annotation? Can you share the Pod/Deployment spec?

**Comment by myugan** [comment]
There is no annotation in the pod. Here is the manifest file.

```
apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
  labels:
    os: ubuntu
spec:
  containers:
  - image: ubuntu
    command:
      - "sleep"
      - "604800"
    imagePullPolicy: IfNotPresent
    name: ubuntu
  restartPolicy: Always
```

I have checked the Pod annotation, and it says the policy is enabled as well.

```
...[SNIP]...
    cni.projectcalico.org/containerID: 08d1ca3a983909decb7b3a73c041105a48b6fbc70fdc69311acca739be8033ba
    cni.projectcalico.org/podIP: 192.168.94.9/32
    cni.projectcalico.org/podIPs: 192.168.94.9/32
    kubearmor-policy: enabled
    kubearmor-visibility: process,file,network,capabilities
```

**Comment by sh1nnyboy** [comment]
Got the same issue, any idea @daemon1024 ?

```
apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-ubuntu-net-icmp-block
  namespace: default
spec:
  selector:
    matchLabels:
      os: ubuntu-util
  network:
    matchProtocols:
    - protocol: icmp
  action:
    Block
```

**Comment by TheWeak3stLink** [comment]
It seems like you have kubearmor in audit mode, not block. I'm my case I'm having the same issue, but I configured the policy in block mode using annotations:

![image](https://github.com/user-attachments/assets/bea48fd4-ab6e-4173-bd66-8b2077d83e0e)

Policy definiton:

```
apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-mysql-block
  namespace: default
spec:
  message: "Block /var/lib/mysql/"
  severity: 5
  selector:
    matchLabels:
      name: mysql-pod
  file:
    matchDirectories:
    - dir: /var/lib/mysql/
      recursive: true
  action:
    Block
```

Karmor probe output:

![image](https://github.com/user-attachments/assets/9846dcd9-da56-4a48-ad3d-0475bf8b07b2)

But I'm able to create files under /var/lib/mysql/ without being blocked.
