### ISSUE TITLE
Container policies incorrectly applied at cluster level

### ISSUE THREAD

**Issue by carlosrodfern** [kubearmor/KubeArmor#1840]
## Bug Report

**General Information**

This is happening in AWS EKS.
K8s version: v1.28.11-eks-db838b0.
KubeArmor: v1.4.0.
Kernel: 5.10.217-205.860.amzn2.x86_64

**To Reproduce**

A very simple policy:

```
apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: generic-maint-tools-access
  namespace: myapplication
spec:
  action: Audit
  message: Restricted maintenance tool access attempt detected
  process:
    matchDirectories:
      - dir: /sbin/
        recursive: true
      - dir: /usr/sbin/
        recursive: true
  selector:
    matchLabels:
      security: generic
  severity: 1
  tags:
    - PCI_DSS
    - MITRE
    - MITRE_T1553_Subvert_Trust_Controls
```

All bpf-containerd pods log this:

```
Detected a Security Policy (added/myapplication/generic-maint-tools-access)
```

However, a few hours later, I get these logs:

```
{
...
  "NamespaceName": "anothernamespace",
  "Owner":
    { "Ref": "StatefulSet", "Name": "somests", "Namespace": "anothernamespace" },
  "PodName": "somepod-2",
  "Labels": "...",
  "ContainerID": "...",
  "ContainerName": "somecontainername",
  "ContainerImage": "...",
  "HostPPID": ...,
  "HostPID": ...,
  "PPID": ...,
  "PID": ...,
  "UID": ...,
  "ParentProcessName": "...",
  "ProcessName": "...",
  "PolicyName": "generic-maint-tools-access",
  "Severity": "1",
  "Tags": "PCI_DSS,MITRE,MITRE_T1553_Subvert_Trust_Controls",
  "ATags": ["PCI_DSS", "MITRE", "MITRE_T1553_Subvert_Trust_Controls"],
  "Message": "Restricted maintenance tool access attempt detected",
  "Type": "MatchedPolicy",
  "Source": "....",
  "Operation": "Process",
  "Resource": "...",
  "Data": "syscall=SYS_EXECVE",
  "Enforcer": "eBPF Monitor",
  "Action": "Audit",
  "Result": "Passed",
  "Cwd": "/",
  ...
}
```

I have no other policy named `generic-maint-tools-access` in any other namespace, or cluster policy named like that.

**Expected behavior**

Container policies are not incorrectly applied to other namespaces.

**Screenshots**
