### ISSUE TITLE
system monitor policyMatcher allows telemetry with empty processName

### ISSUE THREAD

**Issue by rksharma95** [kubearmor/KubeArmor#1931]
## Bug Report

**General Information**

- Environment description: `k3s v1.30.6+k3s1`
- Kernel version (run `uname -a`): `6.6.63-1-lts`
- Orchestration system version in use (e.g. `kubectl version`, ...)
  ```
  Client Version: v1.30.6+k3s1
  Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
  Server Version: v1.30.6+k3s1
  ```
- Link to relevant artifacts (policies, deployments scripts, ...)
- Target containers/pods

**To Reproduce**
- to replicate the behaviour modify kubearmor to ignore `/usr/bin/date` 
  ```
  if path == "/usr/bin/date" {
    return ""
  }
  ```
https://github.com/kubearmor/KubeArmor/blob/f3902690c2a03ffb4df49a7c153ff3ba5f64cb3c/KubeArmor/monitor/processTree.go#L273
https://github.com/kubearmor/KubeArmor/blob/f3902690c2a03ffb4df49a7c153ff3ba5f64cb3c/KubeArmor/monitor/processTree.go#L300

- deploy nginx deployment 
  ```
  kubectl create deployment nginx --image=nginx
  ```
- apply ksp
  ```
  apiVersion: security.kubearmor.com/v1
  kind: KubeArmorPolicy
  metadata:
    name: ksp-nginx-allow-bin-dir-process
  spec:
    action: Allow
    process:
      matchDirectories:
      - dir: /bin/
        recursive: true
    selector:
      matchLabels:
        app: nginx
  ```
- observe kubearmor telemetry in a seperate terminal
  ```
  karmor logs
  ```
- execute inside nginx pod
  ```
  /usr/bin/date +%Y-%m-%d %H:%M:%S
  ```
**Expected behavior**

if processName is empty, telemetry should use source information as processName

**Screenshots**
![Screenshot From 2025-01-03 10-11-26](https://github.com/user-attachments/assets/632eede9-3a8b-4b9a-8363-71ddc8815178)

ProcessName is not present in the telemetry.
