### ISSUE TITLE
ssh exec

### ISSUE THREAD

**Issue by soorya-knox** [kubearmor/KubeArmor#2008]
## Feature Request

**Short Description**

Enable KubeArmor to detect SSH exec events on machines where KubeArmor is running, particularly in VM mode.

**Is your feature request related to a problem? Please describe the use case.**

Currently, KubeArmor does not provide visibility into SSH exec events on the host/VM. This makes it difficult for security operators to monitor remote logins and command executions performed via SSH, which are critical indicators of potential compromise or unauthorized access. Without this visibility, auditing and detecting suspicious activity through SSH becomes incomplete.

**Describe the solution you'd like**

Extend KubeArmor’s detection capabilities to include SSH exec events on the host/VM.

Detect/block when an SSH session is opened.

**Proposed policy design**
Keeping this as part of the preset interface, we propose this policy design -
```yml
apiVersion: security.kubearmor.com/v1
kind: KubeArmorHostPolicy
metadata:
  name: hsp-kubearmor-disallow-ssh-logins
spec:
  nodeSelector:
    matchLabels:
      kubernetes.io/hostname: kubearmor-dev
  severity: 5
  presets:
  - action: Block
     name: ssh
```
