### ISSUE TITLE
Fix readOnly policy match condition

### ISSUE THREAD

**Issue by oneiro-naut** [kubearmor/KubeArmor#352]
## Bug Report
**General Information**

- Environment: vagrant-dev-env(kubearmor-dev-next)
- Kernel version: `Linux kubearmor-dev-next 5.13.0-14-generic #14-Ubuntu SMP Mon Aug 2 12:43:35 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`
- Orchestration system version in use (e.g. `kubectl version`, ...)
```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.1", GitCommit:"632ed300f2c34f6d6d15ca4cef3d3c7073412212", GitTreeState:"clean", BuildDate:"2021-08-19T15:45:37Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.4", GitCommit:"3cce4a82b44f032d0cd1a1790e6d2f5a55d20aae", GitTreeState:"clean", BuildDate:"2021-08-11T18:10:22Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"linux/amd64"}
```
- Link to relevant artifacts (policies, deployments scripts, ...)
- Target containers/pods

**To Reproduce**

1. Apply a KubeArmorPolicy with action as `Audit` or `Allow` having `readOnly` for some file path. For example-
```
apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-ubuntu-4-file-path-readonly-audit
  namespace: multiubuntu
spec:
  severity: 10
  message: "a critical file was accessed"
  tags:
  - WARNNING
  selector:
    matchLabels:
      container: ubuntu-4
  file:
    matchPaths:
    - path: /credentials/password # echo "test" >> /credentials/password (should get log, write op)
      readOnly: true # cat /credentials/password (should get no log, readOnly op)
  action:
    Audit
```
2. Perform read operation on that file using `cat <file_path>` command inside the corresponding pod. 
```
vagrant@kubearmor-dev-next:~$ kubectl exec -ti -n multiubuntu ubuntu-4-deployment-666b6dd9-mfmxl -- bash
root@ubuntu-4-deployment-666b6dd9-mfmxl:/# cat /credentials/password
password file
```
3. Check generated logs. There will be a MatchedPolicy log generated for the read operation just performed. Notice that there is a `O_RDONLY` flag in the log.
```
Policy","source":"/bin/cat /credentials/password","operation":"File","resource":"/credentials/password","data":"syscall=SYS_OPENAT fd=-100 flags=O_RDONLY","action":"Audit","result":"Passed"}
```
**Expected behavior**
We shouldn't get MatchedPolicy log for read operation when the event has O_RDONLY flag set.
