### ISSUE TITLE
Fix ownerOnly policy match condition for audit policies

### ISSUE THREAD

**Issue by oneiro-naut** [kubearmor/KubeArmor#353]
## Bug Report
**General Information**

- Environment: vagrant-dev-env(kubearmor-dev-next)
- Kernel version: `Linux kubearmor-dev-next 5.13.0-14-generic #14-Ubuntu SMP Mon Aug 2 12:43:35 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`
- Orchestration system version in use (e.g. `kubectl version`, ...)
```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.1", GitCommit:"632ed300f2c34f6d6d15ca4cef3d3c7073412212", GitTreeState:"clean", BuildDate:"2021-08-19T15:45:37Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.4", GitCommit:"3cce4a82b44f032d0cd1a1790e6d2f5a55d20aae", GitTreeState:"clean", BuildDate:"2021-08-11T18:10:22Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"linux/amd64"}
```
- Link to relevant artifacts (policies, deployments scripts, ...)
- Target containers/pods

**To Reproduce**

1. Apply a KubeArmorPolicy with action as `Audit` having `ownerOnly` for some file path(or some process path). For example-
```
apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-ubuntu-3-file-path-owner-audit
  namespace: multiubuntu
spec:
  severity: 7
  selector:
    matchLabels:
      container: ubuntu-3
  file:
    matchPaths:
    - path: /home/user1/secret_data1.txt  
      ownerOnly: true
  action:
    Audit
```
2. Switch to that user using `su - <user_name>`. Access that file.
```
vagrant@kubearmor-dev-next:~$ kubectl exec -ti -n multiubuntu ubuntu-3-deployment-59bf5f5564-tsft2 -- bash
root@ubuntu-3-deployment-59bf5f5564-tsft2:/# su - user1
user1@ubuntu-3-deployment-59bf5f5564-tsft2:~$ echo "this is secret" >> secret_data1.txt 
user1@ubuntu-3-deployment-59bf5f5564-tsft2:~$ ls -l
total 16
-rwxrwxr-x 1 user1 user1 8304 Jul 13 10:15 hello
-rw-rw-r-- 1 user1 user1   15 Sep 15 07:29 secret_data1.txt
```
3. Check UID of the owner using `cat /etc/passwd | grep <user_name>` . Here it's 1000.
```
user1@ubuntu-3-deployment-59bf5f5564-tsft2:~$ cat /etc/passwd|grep user1
user1:x:1000:1000::/home/user1:/bin/bash
```
4. Check generated logs. There will be a MatchedPolicy log generated for the echo command used by owner in step 2. Notice that the UID is 1000 flag in the log.
```
{"timestamp":1631695097,"updatedTime":"2021-09-15T08:38:17.719589Z","hostName":"kubearmor-dev-next","namespaceName":"multiubuntu","podName":"ubuntu-3-deployment-59bf5f5564-tsft2","containerID":"e928f60608f10f11fd79903458b9658515640d0721900df9c0c3b6e3b01478ee","containerName":"ubuntu-3-container","hostPid":99747,"ppid":271,"pid":279,"uid":1000,"policyName":"ksp-ubuntu-3-file-path-owner-audit","severity":"7","type":"MatchedPolicy","source":"/bin/cat /home/user1/secret_data1.txt","operation":"File","resource":"/home/user1/secret_data1.txt","data":"syscall=SYS_OPENAT fd=-100 flags=O_RDONLY","action":"Audit","result":"Passed"}
```
**Expected behavior**
We shouldn't get MatchedPolicy log for owner file accesses as it is permitted in the policy and is not a violation. This needs to be ensured for both Process and File ownerOnly operations.
