### ISSUE TITLE
dir + fromSource(path) doesn't work.

### ISSUE THREAD

**Issue by vaibhavmew** [kubearmor/KubeArmor#378]
## Bug Report

**General Information**

- Environment description - vagrant-dev-env
- Kernel version - Linux kubearmor-dev 4.15.0-154-generic #161-Ubuntu SMP Fri Jul 30 13:04:17 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

- Orchestration system version in use - Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.1", GitCommit:"632ed300f2c34f6d6d15ca4cef3d3c7073412212", GitTreeState:"clean", BuildDate:"2021-08-19T15:45:37Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.4", GitCommit:"3cce4a82b44f032d0cd1a1790e6d2f5a55d20aae", GitTreeState:"clean", BuildDate:"2021-08-11T18:10:22Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"linux/amd64"}

- Target container- ubuntu-2

**To Reproduce**

1. Apply the following policy.
```
apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: example1
  namespace: multiubuntu
spec:
  severity: 5
  message: "No message"
  selector:
    matchLabels:
      container: ubuntu-2
  process:
    matchDirectories:
    - dir: /home/user1/
      fromSource:
      - path: /bin/bash
  action:
    Block
```
2. Get into /home/user1. Execute './sleep 1'. Instead of getting 'Permission Denied' the process runs.

**Expected behavior**
process execution blocked

**Actual behavior**
the process runs
