### ISSUE TITLE
path + ownerOnly + fromSource(path) not working

### ISSUE THREAD

**Issue by vaibhavmew** [kubearmor/KubeArmor#380]
## Bug Report

**General Information**

- Environment description - vagrant-dev-env
- Kernel version - Linux kubearmor-dev 4.15.0-154-generic update kubearmor labels and docs #161-Ubuntu SMP Fri Jul 30 13:04:17 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
- Orchestration system version in use - 
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.1", GitCommit:"632ed300f2c34f6d6d15ca4cef3d3c7073412212", GitTreeState:"clean", BuildDate:"2021-08-19T15:45:37Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.4", GitCommit:"3cce4a82b44f032d0cd1a1790e6d2f5a55d20aae", GitTreeState:"clean", BuildDate:"2021-08-11T18:10:22Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"linux/amd64"}

- Target containers - ubuntu-2

**To Reproduce**

1. Instruction 1 - Apply the following policy
```
apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: example1
  namespace: multiubuntu
spec:
  severity: 5
  message: "No message"
  selector:
    matchLabels:
      container: ubuntu-2
  process:
    matchPaths:
    - path: /home/user1/sleep
      ownerOnly: true
      fromSource:
      - path: /bin/bash
  action:
    Allow

```
2. Steps
3. Execute ` /bin/bash `. Now enter /home/user1. Execute sleep as root => Allowed. Execute sleep as user1. Denied.
4. Enter`sh` and try the same commands. You should not be able to run it even as root because only bash is allowed.  
3. Only the owner of the process is allowed. Also the shell should not be anything other than bash.

**Expected behavior**
`./sleep 1` is blocked if run from dash 
 **Actual behavior**
sleep works
