### ISSUE TITLE
Check the feasibility of PodPreset/PodSecurityPolicy

### ISSUE THREAD

**Issue by nam-jaehyun** [kubearmor/KubeArmor#5]
- Current status

In order to apply security contexts (e.g., AppArmor profiles), 
we need to specifically define them in pod definitions for Kubernetes.

Here is an example.

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-1-deployment
  namespace: multiubuntu
  labels:
    deployment: ubuntu-1
spec:
  replicas: 1
  selector:
    matchLabels:
      group: group-1
      container: ubuntu-1
  template:
    metadata:
      labels:
        group: group-1
        container: ubuntu-1
      annotations:
        container.apparmor.security.beta.kubernetes.io/ubuntu-1-container: localhost/apparmor-demo-ubuntu-1
    spec:
      containers:
        - name: ubuntu-1-container
          image: 0x010/ubuntu-w-utils:latest
```

As you can see, we manually added an annotation to use AppArmor for container security.
This document ([Link](https://kubernetes.io/docs/tutorials/clusters/apparmor/)) provides more details.

- What we want to do

We're looking for a way to automatically add security contexts into pod definitions.

For example, we want to automatically add an annotation like 
"container.apparmor.security.beta.kubernetes.io/[container-name]: localhost/apparmor-[namespace name]-[container name]" in this definition.

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-1-deployment
  namespace: multiubuntu
  labels:
    deployment: ubuntu-1
spec:
  replicas: 1
  selector:
    matchLabels:
      group: group-1
      container: ubuntu-1
  template:
    metadata:
      labels:
        group: group-1
        container: ubuntu-1
    spec:
      containers:
        - name: ubuntu-1-container
          image: 0x010/ubuntu-w-utils:latest
```

Here, we don't need to worry about the existence of an AppArmor profile.
KubeArmor will internally create the profile for you.
