### ISSUE TITLE
Apply native apparmor (or any LSM) policy using KubeArmor

### ISSUE THREAD

**Issue by nyrahul** [kubearmor/KubeArmor#54]
KubeArmor allows one to specify the YAML policy which in turn gets converted/mapped into app-armor or underlying LSM based policy spec.

It should be possible to specify the native app-armor (or other LSM) policy as it is in YAML so that we do not depend on the KubeArmor extensions to be added for supporting all the AppArmor constructs.

A sample YAML could be:
```yaml
--- 
apiVersion: security.accuknox.com/v1
kind: KubeArmorPolicy
metadata: 
  name: ksp-mysql-dir-audit
  namespace: wordpress-mysql
spec: 
  apparmor: |
        /bin/bzip2 rm,
        /** r,
        signal peer=/usr/bin/man,
  selector: 
    matchLabels: 
      app: mysql
```
Notice the AppArmor specific constructs included in native AppArmor format.
