### ISSUE TITLE
VM policy is not blocking the process from same ssh window

### ISSUE THREAD

**Issue by salman-accuknox** [kubearmor/KubeArmor#554]
## Bug Report

**General Information**

- Environment description: Debian 11 VM (GCP- Compute Engine)
- Kernel version (run `uname -a`)
```
Linux instance-1 5.10.0-9-cloud-amd64 #1 SMP Debian 5.10.70-1 (2021-09-30) x86_64 GNU/Linux
```
- Link to relevant artifacts: https://help.accuknox.com/open-source/kubearmor-vm/
- Target: VM

**To Reproduce**

1. Apply policy on VM
``` YAML
apiVersion: security.kubearmor.com/v1
kind: KubeArmorHostPolicy
metadata:
  name: hsp-kubearmor-cat-block
spec:
  process:
    matchPaths:
    - path: /usr/bin/cat
  action:
    Block
```

2. Validate the policy by using the cat 
```
cat cat-block.yaml
```

**Expected behavior**

-bash: /usr/bin/cat: Permission denied

**Current Behavior**
File is shown in the terminal
```
slmnpj93@instance-1:~$ cat cat-block.yaml 
apiVersion: security.kubearmor.com/v1
kind: KubeArmorHostPolicy
metadata:
  name: hsp-kubearmor-cat-block
spec:
  process:
    matchPaths:
    - path: /usr/bin/cat
  action:
    Block
slmnpj93@instance-1:~
```
If I am executing the process from the other ssh window, At that time I m getting the result correct. 
```
slmnpj93@instance-1:~$ cat cat-block.yaml 
-bash: /usr/bin/cat: Permission denied
slmnpj93@instance-1:~$
```

**Logs**
When executing the process from the existing ssh window
```
{"Timestamp":1640748695,"UpdatedTime":"2021-12-29T03:31:35.584266Z","ClusterName":"Default","HostName":"instance-1","HostPID":7255,"PPID":669,"PID":7255,"UID":1001,"PolicyName":"hsp-kubearmor-cat-block","Severity":"1","Type":"MatchedHostPolicy","Source":"bash","Operation":"Process","Resource":"/usr/bin/cat cat-block.yaml","Data":"syscall=SYS_EXECVE","Action":"Block","Result":"Passed"}
```
When executing the process from new ssh window
```
{"Timestamp":1640748785,"UpdatedTime":"2021-12-29T03:33:05.249415Z","ClusterName":"Default","HostName":"instance-1","HostPID":7295,"PPID":7290,"PID":7295,"UID":1001,"PolicyName":"hsp-kubearmor-cat-block","Severity":"1","Type":"MatchedHostPolicy","Source":"bash","Operation":"Process","Resource":"/usr/bin/cat cat-block.yaml","Data":"syscall=SYS_EXECVE","Action":"Block","Result":"Permission denied"}
```
