### ISSUE TITLE
Auto-annotating the service/pod with apparmor annotations

### ISSUE THREAD

**Issue by nyrahul** [kubearmor/KubeArmor#59]
Currently, the AppArmor annotations have to be manually applied before deploying the service/pods.

For e.g., from [examples/wordpress-mysql](https://github.com/accuknox/KubeArmor/blob/master/examples/wordpress-mysql/wordpress-mysql-deployment.yaml) example deployment contains the manually added AppArmor annotation:
```yaml
::
  template:
    metadata:
      labels:
        app: wordpress
      annotations:
        container.apparmor.security.beta.kubernetes.io/wordpress: localhost/apparmor-wordpress
::
```
The AppArmor related annotations should be automatically applied if KubeArmor operator is deployed in the cluster.
