### ISSUE TITLE
TCP log not matched to a policy

### ISSUE THREAD

**Issue by daemon1024** [kubearmor/KubeArmor#620]
## Bug Report

**General Information**

- Environment description (GKE, VM-Kubeadm, vagrant-dev-env, minikube, microk8s, ...) all
- Kernel version (run `uname -a`) Linux kubearmor-dev-all 4.15.0-156-generic Ubuntu SMP Thu Aug 19 23:31:58 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
- Orchestration system version in use (e.g. `kubectl version`, ...) v1.23.3
- Link to relevant artifacts (policies, deployments scripts, ...) vagrant dev env, multiubuntu pod set

**To Reproduce**

1. Apply a `tcp` allow from source policy. Like
```yaml
apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-ubuntu-5-net-tcp-allow
  namespace: multiubuntu
spec:
  severity: 8
  selector:
    matchLabels:
      container: ubuntu-5
  network:
    matchProtocols:
    - protocol: tcp
      fromSource:
      - path: /usr/bin/curl
  action:
    Allow
 ```
2. Generate a TCP based event. For eg 
![image](https://user-images.githubusercontent.com/47106543/153927689-c00007ed-576b-4535-a0fa-a2ea657fca01.png)

**Expected behavior**

No network log for TCP event

**Current Behavior**
Generates the following system log
```json
{"Timestamp":1644864495,"UpdatedTime":"2022-02-14T18:48:15.489080Z","ClusterName":"default","HostName":"kubearmor-dev-all","NamespaceName":"multiubuntu","PodName":"ubuntu-5-deployment-7778f46c67-nfvzb","ContainerID":"9f6ad71bb941e7ebcd88ed789b91fbfbdf500372c8973e152aa9f5e5196e6aeb","ContainerName":"ubuntu-5-container","HostPID":16361,"PPID":599,"PID":609,"Type":"ContainerLog","Source":"/usr/bin/curl 142.251.42.46","Operation":"Network","Resource":"sa_family=AF_INET sin_port=80 sin_addr=142.251.42.46","Data":"syscall=SYS_CONNECT fd=3","Result":"Operation now in progress","ContainerImage":"kubearmor/ubuntu-w-utils:0.1@sha256:38f147a486036e3ae5af0ad94b25bd63a5a70b0b24420fde15fc635d9692a049"}
```
cc @nyrahul @nam-jaehyun
