### ISSUE TITLE
supporting `protocol: raw` in matchProtocols

### ISSUE THREAD

**Issue by nyrahul** [kubearmor/KubeArmor#676]
## Feature Request

**Short Description**

Kubearmor supports enforcement of network primitives (tcp|udp|icmp) at the process level. A simple example is:
```yaml
apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: autopol-system-196416118
  namespace: wordpress-mysql
spec:
  severity: 1
  selector:
    matchLabels:
      app: wordpress
  network:
    matchProtocols:
    - protocol: raw 
      fromSource:
      - path: /usr/sbin/apache2
    - protocol: tcp 
      fromSource:
      - path: /bin/bash
      - path: /usr/sbin/apache2
    - protocol: udp 
      fromSource:
      - path: /usr/sbin/apache2
  action: Allow
```

Currently, `raw` is not supported as the protocol type. However, the [discovery-engine](https://github.com/accuknox/discovery-engine) detects raw connections in the context to the process.

**Describe the solution you'd like**

Apparmor [already supports](https://gitlab.com/apparmor/apparmor/-/wikis/AppArmor_Core_Policy_Reference#note-about-apparmor-23-26-network-rules) raw protocols. Kubearmor needs to handle `raw`, similar to what we do for `tcp|udp|icmp`.
