### ISSUE TITLE
security profile clash when namespace and container-name is same

### ISSUE THREAD

**Issue by nyrahul** [kubearmor/KubeArmor#700]
## Bug Report

kubearmor does not handle properly the situation where there is multiple containers with the same name in the same namespace ( this situation is common when using charts e.g gitlab autodevops) which results in unexpected behavior (policies are not enforced, policies are being applied to wrong containers etc...).

<details><summary>Sample Deployment with same container name (deploy.yaml)</summary>
<p>

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp1
spec:
  selector:
    matchLabels:
      app: myapp1
  template:
    metadata:
      labels:
        app: myapp1
    spec:
      containers:
      - name: ubuntu
        image: ubuntu
        command:
          - "bash"
        args:
          - "-c"
          - "sleep infinity"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp2
spec:
  selector:
    matchLabels:
      app: myapp2
  template:
    metadata:
      labels:
        app: myapp2
    spec:
      containers:
      - name: ubuntu
        image: ubuntu
        command:
          - "bash"
        args:
          - "-c"
          - "sleep infinity"
```

</p>
</details>

<details><summary>Security policy for myapp1 deployment (myapp1-policy.yaml)</summary>
<p>

```yaml
apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: policy1
spec:
  selector:
    matchLabels:
      app: myapp1
  process:
    matchPaths:
    - path: /usr/bin/ls
  action:
    Block
```
</p>
</details>

<details><summary>Security policy for myapp2 deployment (myapp2-policy.yaml)</summary>
<p>

```yaml
apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: policy2
spec:
  selector:
    matchLabels:
      app: myapp2
  process:
    matchPaths:
    - path: /usr/bin/cat
  action:
    Block
```
</p>
</details>

**General Information**

- Environment description: Any
- Kernel version: ANY
- Orchestration system version in use (e.g. `kubectl version`, ...): ANY
- Link to relevant artifacts (policies, deployments scripts, ...): Given in the description above

**To Reproduce**

1. `kubectl apply -f deploy.yaml`
2. `kubectl apply -f myapp1-policy.yaml`

This policy should impact only myapp1, but currently this will also apply the rules to myapp2.

**What is the root cause?**
Currently, we create an apparmor profile using following template `kubearmor-NAMESPACE-CONTAINERNAME`. Thus if there are multiple deployments in the same namespace having same containername then it would apply to all the similar deployments.

**Expected behavior**

Applying `myapp1-policy.yaml` should not impact myapp2 deployment.

**Possible Solution**

Add pod name (without instance id) to the security profile template name for eg. `kubearmor-NAMESPACE-PODNAME-CONTAINERNAME`.

Credits to @achrefbensaad for discovering this issue and reporting it in detail on slack. Thanks
