### ISSUE TITLE
matchPatterns are not working in `action: Block` rule

### ISSUE THREAD

**Issue by yasin-cs-ko-ak** [kubearmor/KubeArmor#793]
## Bug Report

**General Information**

- Environment description - GKE
- Kernel version - `Linux mysql-58cdf6ccf-zp6wm 5.10.109+ #1 SMP Tue May 24 09:08:48 UTC 2022 x86_64 GNU/Linux`
- Orchestration system version in use
```
kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.2", GitCommit:"f66044f4361b9f1f96f0053dd46cb7dce5e990a8", GitTreeState:"archive", BuildDate:"2022-06-18T07:33:51Z", GoVersion:"go1.18.3", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.10-gke.600", GitCommit:"2c921d7b040ed9c5a3a1f9407fb109b74d72d0a4", GitTreeState:"clean", BuildDate:"2022-06-02T09:20:24Z", GoVersion:"go1.16.15b7", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.24) and server (1.22) exceeds the supported minor version skew of +/-1
```
- Link to relevant artifacts 
Deployments:-
`kubectl apply -f https://raw.githubusercontent.com/kubearmor/KubeArmor/main/examples/wordpress-mysql/wordpress-mysql-deployment.yaml`
Policy:-
```yaml
apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-mysql-block-chmod-777-mal
  namespace: wordpress-mysql
spec:
  severity: 5
  selector:
    matchLabels:
      app: mysql
  process:
    matchPatterns:
    - pattern: /*/chmod 777 mal
  action: Block
```
- Target containers/pods
MySQL
**To Reproduce**

1. Instruction 
- Deploy this deployment `kubectl apply -f https://raw.githubusercontent.com/kubearmor/KubeArmor/main/examples/wordpress-mysql/wordpress-mysql-deployment.yaml`
- Apply the policy mentioned above and try to run that `chmod 777 mal` command inside the mysql pod.

**Expected behavior**
Expected behaviour is `Permission Denied`
But it is not working and If I change that to `action: Audit` it's working fine and generating logs as shown below.
Policy:-
```yaml
apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-mysql-audit-chmod-777-mal
  namespace: wordpress-mysql
spec:
  severity: 5
  selector:
    matchLabels:
      app: mysql
  process:
    matchPatterns:
    - pattern: /*/chmod 777 mal
  action: Audit
```
Logs:-
```
== Alert / 2022-07-29 10:38:15.729771 ==
ClusterName: default
HostName: gke-cys-july-28-default-pool-1981dfbd-gr33
NamespaceName: wordpress-mysql
PodName: mysql-58cdf6ccf-7b9km
Labels: app=mysql
ContainerName: mysql
ContainerID: 7a5622a391a4faeb9fcc4c1f8d598421b6834944e30e8f3b57d1164156902107
ContainerImage: docker.io/library/mysql:5.6@sha256:20575ecebe6216036d25dab5903808211f1e9ba63dc7825ac20cb975e34cfcae
Type: MatchedPolicy
PolicyName: ksp-mysql-block-sleep-5
Severity: 5
Source: /bin/bash
Resource: /bin/chmod 777 mal
Operation: Process
Action: Audit
Data: syscall=SYS_EXECVE
Enforcer: eBPF Monitor
Result: Passed
HostPID: 704536
HostPPID: 703656
PID: 605
PPID: 594
ParentProcessName: /bin/bash
ProcessName: /bin/chmod
```
A description of what you expected to happen.
It should block the `chmod` command from the execution.

**Screenshots**
I have tested for matchPattern with action: Block , but It’s not working and even not generating the log. 
![image](https://user-images.githubusercontent.com/92008211/182533469-7f8da8a5-39c2-4f15-853e-852a6f873408.png)
In case of action: Audit, It works fine and generating logs.
![image](https://user-images.githubusercontent.com/92008211/182533502-2a39472d-53ee-45b2-b03f-d1f6a8cd7485.png)

Kindly look into this.
cc: @nyrahul
