### ISSUE TITLE
Policy enforcement failure due to rule conflicts

### ISSUE THREAD

**Issue by nam-jaehyun** [kubearmor/KubeArmor#86]
Let's say that we have the following policies.

Policy A
```
process:
  matchPaths:
  - path: /bin/sleep
     fromSource:
     - path: /bin/bash
  action:
    Allow
```

Policy B
```
process:
  matchPaths:
  - path: /bin/bash
action:
  Allow
```

Those policies are converted something like this.

```
...
/bin/bash cx,
profile /bin/bash {
  /bin/sleep ix,
}
/bin/bash ix,
...
```

Causing the policy enforcement failure because of two /bin/bash lines.

**Comment by daemon1024** [comment]
Hi, I am working on this. Could this issue be assigned to me?

**Comment by nam-jaehyun** [comment]
@daemon1024 I assigned this issue to you.

**Comment by daemon1024** [comment]
Hey, I think have got an understanding of the problem.

https://github.com/accuknox/KubeArmor/blob/38fc028685a3864f4485c05ff65ec78962f5eca6/KubeArmor/enforcer/appArmorProfile.go#L15

Currently we check `paths` and `FromSource paths` independently, we need to check such that sources shouldn't have any conflicts with processes white/blacklists.

In the example specified in the description, the final construct should be something like
```
/bin/bash cix,
profile /bin/bash {
  /bin/sleep ix,
}
```

Let me know if I am headed into the right direction.

**Comment by nam-jaehyun** [comment]
@daemon1024 Yes, that was what I thought, but I'm wondering if there is no problem when we have such AppArmor rules.
If you validate those AppArmor rules before starting the implementation, it would be helpful.
Please check if there is no syntax and semantic error.

**Comment by nam-jaehyun** [comment]
@daemon1024 any update on this issue?

**Comment by daemon1024** [comment]
Hey @nam-jaehyun, I have been working on #170 so haven't made any progress here.

**Comment by nam-jaehyun** [comment]
@daemon1024 no problem :) just for checking.

**Comment by daemon1024** [comment]
Not blocking this if someone else wants to take it up meanwhile. I believe I have already been unassigned on the xlsx.

**Comment by daemon1024** [comment]
>I'm wondering if there is no problem when we have such AppArmor rules.

@nam-jaehyun It does error out,

AppArmor does have issues with rule conflicts,

`profile kubearmor-multiubuntu-ubuntu-1-container: has merged rule /bin/bash with conflicting x modifiers
ERROR merging rules for profile kubearmor-multiubuntu-ubuntu-1-container, failed to load`

I had both cx and ix rules, but using cix solved it. 

So should I proceed with https://github.com/kubearmor/KubeArmor/issues/86#issuecomment-865012233?

**Comment by elfadel** [comment]
Please, assign it to me.

**Comment by elfadel** [comment]
This issue/bug is definitely unreproductible, at least under my environment (I am using kubearmor-dev vagrant box).
Below, I describe how I proceed to reproduce the bug.

**Comment by elfadel** [comment]
Let's consider this policy first:
```
apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: reproduce-issue-86-1
  namespace: multiubuntu
spec:
  severity: 5
  message: "block the ls command"
  selector:
    matchLabels:
      group: group-1
  process:
    matchPaths:
    - path: /bin/ls
      fromSource:
      - path: /bin/bash
    - path: /bin/bash
  action:
    Block
```
It will be converted in the following apparmor policy:
```
...
deny /bin/bash x,
/bin/bash cx,
profile /bin/bash {
  /bin/bash rix,
  ...
  deny /bin/bash x,
  deny /bin/ls x,
  ...
}
...
```
The above policy will be correctly enforced and works as expected, i.e., `bash` will be blocked. Here we cannot test `ls` as far as bash is blocked.

**Comment by elfadel** [comment]
Now Let's take a second example.

Policy A:
```
apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: reproduce-issue-86-1
  namespace: multiubuntu
spec:
  severity: 5
  message: "block the ls command"
  selector:
    matchLabels:
      group: group-1
  process:
    matchPaths:
    - path: /bin/ls
      fromSource:
      - path: /bin/bash
  action:
    Block
```

Policy B:
```
apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: reproduce-issue-86-2
  namespace: multiubuntu
spec:
  severity: 5
  message: "block/allow the bash command"
  selector:
    matchLabels:
      group: group-1
  process:
    matchPaths:
    - path: /bin/bash
  action:
    Allow
```

Those policies are converted as:
```
...
/bin/bash ix,
/bin/bash cx,
profile /bin/bash {
  /bin/bash rix,
  ...
  /bin/bash ix,
  deny /bin/ls x,
  ...
}
...
```

Here also, the enforcement going well: no conflict because of two `/bin/bash` lines. And the policies work as expected, i.e., the `ls` is blocked from `/bin/bash`, and allowed otherwise.
