### ISSUE TITLE
specify multiple protocols, capabilities in the same rule

### ISSUE THREAD

**Issue by nyrahul** [kubearmor/KubeArmor#91]
KubeArmor currently allows enabling/disabling network protocols and system capabilities, one protocol/cap at a time.
It should be possible to specify multiple protocols or system capabilities in the same rule.

For e.g, if the user wants to enable TCP and UDP protocols (and not ICMP), then the user has to specify two different rules i.e, one enabling TCP and the other enabling UDP. Following is the policy specification in the context:
```yaml
network:
    matchProtocols:
    - protocol: [TCP|UDP|ICMP]       #---> Only TCP or UDP or ICMP could be specified.
      fromSource:
      - path: [absolute file path]
      - dir: [absolute directory path]
        recursive: [true:false]
```

It should be possible to specify multiple protocols in the same rule using the following (prospective) spec:
```yaml
network:
    matchProtocols:
    - protocol: [TCP,UDP,ICMP]    #---> Use comma separated protocols to specify multiple protocols.
      fromSource:
      - path: [absolute file path]
      - dir: [absolute directory path]
        recursive: [true:false]
```

The same is true for specifying multiple system capabilities.
