### ISSUE TITLE
KubeArmor policy breaking wordpress application

### ISSUE THREAD

**Issue by vishnusomank** [kubearmor/KubeArmor#911]
## Bug Report

**General Information**

- Environment: GKE
- Version: 1.22.12-gke.300
- Policy used
  ```
  apiVersion: security.kubearmor.com/v1
  kind: KubeArmorPolicy
  metadata:
    name: wordpress-knoxuser-wordpress-latest-allow-wordpress-network-access
    namespace: default
  spec:
    action: Allow
    network:
      matchProtocols:
      - fromSource:
        - path: /usr/sbin/apache2
        protocol: raw
      - fromSource:
        - path: /usr/local/bin/apache2-foreground
        - path: /usr/local/bin/php
        - path: /usr/sbin/apache2
        protocol: tcp
      - fromSource:
        - path: /usr/local/bin/php
        - path: /usr/sbin/apache2
        protocol: udp
    selector:
      matchLabels:
        app: wordpress
        tier: frontend
    severity: 1
    tags:
    - Wordpress
    - TCP
    - UDP
    - RAW
    - Network
  ```
- Target containers/pods: `wordpress`

**To Reproduce**

1. Deploy WordPress application [[Link](https://github.com/kubearmor/KubeArmor/tree/main/examples/wordpress-mysql)]
2. Port forward to use the WordPress UI 
    - kubectl port-forward -n wordpress-mysql service/wordpress --address 0.0.0.0 --address :: 8088:80
4. Check `karmor logs`

**Expected behavior**

The application should show the WordPress UI 

**Current behaviour**

The policy is breaking the access to WordPress UI. Once the policy is removed using `kubectl delete` the application starts to work as intended. No deny logs are generated in  `karmor log`

**Further troubleshooting**
The following error messages are generating after the policy applied and tried to access to the UI
```
type=AVC msg=audit(1663934983.207:68531): apparmor="DENIED" operation="accept" profile="kubearmor-wordpress-mysql-wo
rdpress-wordpress" pid=1390470 comm="apache2" lport=80 family="inet6" sock_type="stream" protocol=6 requested_mask="
accept" denied_mask="accept"
type=AVC msg=audit(1663934984.211:68532): apparmor="DENIED" operation="accept" profile="kubearmor-wordpress-mysql-wo
rdpress-wordpress" pid=1390471 comm="apache2" lport=80 family="inet6" sock_type="stream" protocol=6 requested_mask="accept" denied_mask="accept"
```
