### ISSUE TITLE
Block on /proc/ path is not displaying any alerts in karmor log

### ISSUE THREAD

**Issue by seswarrajan** [kubearmor/KubeArmor#941]
## Bug Report

**General Information**

- Environment description (VM)
- Kernel version (5.15.0-50-generic)

**To Reproduce**

1. Run kubearmor in systemd mode.
2. Open a new tab and run karmor log
3. Apply the attached policy yaml using `karmor vm policy add pol.yaml` command.
4. Now once policy is applied, open a new terminal and run `cat /proc/cpuinfo`
5. The action results in **Permission Denied**.

**Policy**
```
apiVersion: security.kubearmor.com/v1
kind: KubeArmorHostPolicy
metadata:
  name: khp-02
spec:
  severity: 5
  file:
    matchPaths:
    - path: /proc/cpuinfo
      fromSource:
      - path: /usr/bin/cat
  action:
    Block
```

**Expected behavior**

An equivalent alert is expected to be displayed in karmor log.

**Screenshots**

karmor log results are empty
