### ISSUE TITLE
KubeArmor policy with readOnly flag not working with BPFLSM

### ISSUE THREAD

**Issue by vishnusomank** [kubearmor/KubeArmor#959]
## Bug Report

**General Information**

- Environment: GKE
- v1.23.8-gke.1900
- Target deployment: wordpress-mysql
- Active LSM: BPFLSM

**To Reproduce**

1. Install [wordpress-mysql](https://github.com/kubearmor/KubeArmor/tree/main/examples/wordpress-mysql) application
    ```
    kubectl apply -f https://raw.githubusercontent.com/kubearmor/KubeArmor/main/examples/wordpress-mysql/wordpress-mysql-deployment.yaml
    ```
2. Run `karmor recommend` on `wordpress-mysql` namespace
    ```
    karmor recommend -n wordpress-mysql 
    ```
3. Apply the following policy
```
apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: mysql-mysql-5-6-system-monitoring-deny-write-under-bin-directory
  namespace: wordpress-mysql
spec:
  action: Block
  file:
    matchDirectories:
    - dir: /bin/
      readOnly: true
      recursive: true
    - dir: /sbin/
      readOnly: true
      recursive: true
    - dir: /usr/sbin/
      readOnly: true
      recursive: true
    - dir: /usr/bin/
      readOnly: true
      recursive: true
  message: Alert! An attempt to write below system binary directories was denied.
  selector:
    matchLabels:
      app: mysql
  severity: 5
  tags:
  - NIST
  - MITRE
  - NIST_800-53_AU-2
  - NIST_800-53_SI-4
  - MITRE_T1036_masquerading
```
**Current behavior**

With the above policy applied, binaries from `/bin/`, `/usr/bin` etc are getting denied, and write below these folders are also permissible

**Expected behavior**

With the above policy applied any write under `/bin/`, `/usr/bin/` etc should be denied. Also, the binaries from this folder should be accessible for read and execute. 

**Karmor Log**
```
== Alert / 2022-10-31 12:25:46.003736 ==
ClusterName: default
HostName: gke-karmor-test-default-pool-0701ac9e-cvg7
NamespaceName: wordpress-mysql
PodName: mysql-5df4cd65d5-wlcw7
Labels: app=mysql
ContainerName: mysql
ContainerID: 5c9f32a9bfbcb8c95bf2e0f081545aa9d098516fbc8f8c145ab0950edfe18fc8
ContainerImage: docker.io/library/mysql:5.6@sha256:20575ecebe6216036d25dab5903808211f1e9ba63dc7825ac20cb975e34cfcae
Type: MatchedPolicy
PolicyName: mysql-mysql-5-6-system-monitoring-deny-write-under-bin-directory
Severity: 5
Message: Alert! An attempt to write below system binary directories denied.
Source: /bin/ls
Resource: /bin/ls
Operation: File
Action: Block
Data: syscall=SYS_OPEN flags=O_RDONLY
Enforcer: BPFLSM
Result: Permission denied
HostPID: 91388
HostPPID: 78895
PID: 305
PPID: 257
ParentProcessName: /bin/bash
ProcessName: /bin/ls
Tags: NIST,MITRE,NIST_800-53_AU-2,NIST_800-53_SI-4,MITRE_T1036_masquerading
```

**Karmor Probe**
```
Found KubeArmor running in Kubernetes

Daemonset :
 	kubearmor 	Desired: 1	Ready: 1	Available: 1	
Deployments : 
 	kubearmor-annotation-manager 	Desired: 1	Ready: 1	Available: 1	
 	kubearmor-host-policy-manager	Desired: 1	Ready: 1	Available: 1	
 	kubearmor-policy-manager     	Desired: 1	Ready: 1	Available: 1	
 	kubearmor-relay              	Desired: 1	Ready: 1	Available: 1	
Containers : 
 	kubearmor-annotation-manager-5b88fc49c-fmlvg  	Running: 2	Image Version: gcr.io/kubebuilder/kube-rbac-proxy:v0.8.0	
 	kubearmor-d8xbl                               	Running: 1	Image Version: kubearmor/kubearmor:stable               	
 	kubearmor-host-policy-manager-7448cbc76f-v5pqk	Running: 2	Image Version: gcr.io/kubebuilder/kube-rbac-proxy:v0.5.0	
 	kubearmor-policy-manager-76575654b8-hq8lm     	Running: 2	Image Version: gcr.io/kubebuilder/kube-rbac-proxy:v0.5.0	
 	kubearmor-relay-5656cc5bf7-hv2px              	Running: 1	Image Version: kubearmor/kubearmor-relay-server:latest  	
Node 1 : 
 	OS Image:                 	Container-Optimized OS from Google	
 	Kernel Version:           	5.10.127+                         	
 	Kubelet Version:          	v1.23.8-gke.1900                  	
 	Container Runtime:        	containerd://1.5.13               	
 	Active LSM:               	BPFLSM                            	
 	Host Security:            	true                              	
 	Container Security:       	true                              	
 	Container Default Posture:	block(File)                       	block(Capabilities)	block(Network)	
 	Host Default Posture:     	block(File)                       	block(Capabilities)	block(Network)	
Armored Up pods : 
+-----------------+-------------------------------------------------------+-------------------------------------------------------------------------------------+
|    NAMESPACE    |                         NAME                          |                                       POLICY                                        |
+-----------------+-------------------------------------------------------+-------------------------------------------------------------------------------------+
| explorer        | knoxautopolicy-5755447fbb-stbqw                       |                                                                                     |
+-----------------+-------------------------------------------------------+-------------------------------------------------------------------------------------+
| kube-system     | kube-proxy-gke-karmor-test-default-pool-0701ac9e-cvg7 |                                                                                     |
+-----------------+-------------------------------------------------------+-------------------------------------------------------------------------------------+
| wordpress-mysql | mysql-5df4cd65d5-wlcw7                                | mysql-mysql-5-6-system-monitoring-deny-write-under-bin-directory                    |
|                 |                                                       | mysql-mysql-5-6-system-owner-discovery mysql-mysql-5-6-audit-access-to-mysqldump    |
|                 |                                                       | mysql-mysql-5-6-cert-access mysql-mysql-5-6-cis-mysql-1-2                           |
|                 |                                                       | mysql-mysql-5-6-least-functionality-execute-package-management-process-in-container |
|                 |                                                       | mysql-mysql-5-6-maintenance-tool-access                                             |
+                 +-------------------------------------------------------+-------------------------------------------------------------------------------------+
|                 | wordpress-c4bf5b44b-f9mgn                             |                                                                                     |
+-----------------+-------------------------------------------------------+-------------------------------------------------------------------------------------+
```
