### ISSUE TITLE
Action: Audit (Block) not Action: Block

### ISSUE THREAD

**Issue by sunnoy** [kubearmor/KubeArmor#970]
## Bug Report

**General Information**

- k3s
- 5.10.134-12.al8.x86_64
- 1.25
```yaml
apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-group-1-proc-path-block
  namespace: default
spec:
  severity: 2
  tags: 
    - tag1
    - tag2
  message: "first policy"
  selector:
    matchLabels:
      app: busybox
  process:
    matchPaths:
    - path: /bin/sleep
  action:
    Block
```

```yaml
spec:
  volumes:
    - name: kube-api-access-8s2rh
      projected:
        sources:
          - serviceAccountToken:
              expirationSeconds: 3607
              path: token
          - configMap:
              name: kube-root-ca.crt
              items:
                - key: ca.crt
                  path: ca.crt
          - downwardAPI:
              items:
                - path: namespace
                  fieldRef:
                    apiVersion: v1
                    fieldPath: metadata.namespace
        defaultMode: 420
  containers:
    - name: busybox
      image: nicolaka/netshoot
      command:
        - /bin/sh
      args:
        - '-c'
        - tail -f /dev/null
      resources: {}
      volumeMounts:
        - name: kube-api-access-8s2rh
          readOnly: true
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      imagePullPolicy: Always
  restartPolicy: Always
  terminationGracePeriodSeconds: 0
  dnsPolicy: ClusterFirst
  serviceAccountName: default
  serviceAccount: default
  nodeName: k3s-2
  securityContext: {}
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              app: nginx
          topologyKey: kubernetes.io/hostname
  schedulerName: default-scheduler
  tolerations:
    - key: node.kubernetes.io/not-ready
      operator: Exists
      effect: NoExecute
      tolerationSeconds: 300
    - key: node.kubernetes.io/unreachable
      operator: Exists
      effect: NoExecute
      tolerationSeconds: 300
  priority: 0
  enableServiceLinks: true
  preemptionPolicy: PreemptLowerPriority
```

**To Reproduce**

1. Instruction 1
2. Instruction 2

**Expected behavior**

Action: Block

**Screenshots**

**Comment by sunnoy** [comment]
2022-11-08 07:41:28.541479	INFO	Supported LSMs: capability,selinux
2022-11-08 07:41:28.541505	INFO	Disabled KubeArmor Enforcer since No LSM is enabled

there are LSMs: capability,selinux but No LSM is enabled

**Comment by daemon1024** [comment]
Hey @sunnoy, Thanks fore reporting. We support LSM only when KubeArmor directly runs on Bare Metal to enforce Host Policies. We require the presence of BPFLSM or AppArmor for container enforcement i.e. KubeArmor Policies.

**Comment by sunnoy** [comment]
We support LSM only when KubeArmor directly runs on Bare Metal to enforce Host Policies.  so the code is 
```go

selinux:
	if !kl.IsInK8sCluster() {
		re.seLinuxEnforcer = NewSELinuxEnforcer(node, logger)
		if re.seLinuxEnforcer != nil {
			re.Logger.Print("Initialized SELinux Enforcer")
			re.EnforcerType = "SELinux"
			logger.UpdateEnforcer(re.EnforcerType)
			return re
		}
	}
```

##  but how to enable the presence of BPFLSM container enforcement ? just apply KubeArmorPolicy ?

i find the code

```go
lsmOrder := flag.String(LsmOrder, "bpf,apparmor,selinux", "lsm preference order to use, available lsms [bpf, apparmor, selinux]")

bpf:
	re.bpfEnforcer, err = be.NewBPFEnforcer(node, logger)
	if re.bpfEnforcer != nil {
		if err != nil {
			re.Logger.Print("Error Initialising BPF-LSM Enforcer, Cleaning Up")
			if err := re.bpfEnforcer.DestroyBPFEnforcer(); err != nil {
				re.Logger.Err(err.Error())
			} else {
				re.Logger.Print("Destroyed BPF-LSM Enforcer")
			}
			goto lsmselection
		}
		re.Logger.Print("Initialized BPF-LSM Enforcer")
		re.EnforcerType = "BPFLSM"
		logger.UpdateEnforcer(re.EnforcerType)
		return re
	}

// NewBPFEnforcer instantiates a objects for setting up BPF LSM Enforcement
func NewBPFEnforcer(node tp.Node, logger *fd.Feeder) (*BPFEnforcer, error) {
```

**Comment by daemon1024** [comment]
@sunnoy It depends on your node/host image. 

/sys/kernel/security/lsm should contain bpf/apparmor.

What is the host OS?
How have you setup your k8s environment?

You can check our support matrix here https://github.com/kubearmor/KubeArmor/blob/main/getting-started/support_matrix.md

**Comment by sunnoy** [comment]
my  env is 

```bash
 
Alibaba Cloud Linux release 3 (Soaring Falcon) "you can think it is centos 8"

5.10.134-12.al8.x86_64

v1.25.2+k3s1

```


Does it just match the os instead of the kernel version?

**Comment by sunnoy** [comment]
i have add bpf in lsm

```bash
Node 2 :
 	OS Image:                 	Alibaba Cloud Linux 3 (Soaring Falcon)
 	Kernel Version:           	5.10.134-12.al8.x86_64
 	Kubelet Version:          	v1.25.2+k3s1
 	Container Runtime:        	containerd://1.6.8-k3s1
 	Active LSM:               	BPFLSM
 	Host Security:            	true
 	Container Security:       	true
 	Container Default Posture:	block(File)                           	block(Capabilities)	block(Network)
 	Host Default Posture:     	block(File)                           	block(Capabilities)	block(Network)


cat /sys/kernel/security/lsm
capability,selinux,bpf
```
<img width="561" alt="image" src="https://user-images.githubusercontent.com/19342276/200790096-43215cfd-3905-49c4-8fa2-8a7acf364c29.png">



```yaml
apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-group-1-proc-path-block
  namespace: default
spec:
  severity: 2
  tags: 
    - tag1
    - tag2
  message: "first policy"
  selector:
    matchLabels:
      app: busybox
  process:
    matchPaths:
    - path: /bin/sleep
  action:
    Block
```

it's can not block ...

**Comment by daemon1024** [comment]
That's weird, it should be blocking. Can you try on some other container. Also is this container running in the node which has BPF LSM enabled?

**Comment by sunnoy** [comment]
i have try doc example contianers 

kubectl apply -f https://raw.githubusercontent.com/kubearmor/KubeArmor/main/examples/multiubuntu/multiubuntu-deployment.yaml


```bash
Found KubeArmor running in Kubernetes

Daemonset :
 	kubearmor 	Desired: 2	Ready: 2	Available: 2
Deployments :
 	kubearmor-policy-manager     	Desired: 1	Ready: 1	Available: 1
 	kubearmor-relay              	Desired: 1	Ready: 1	Available: 1
 	kubearmor-host-policy-manager	Desired: 1	Ready: 1	Available: 1
 	kubearmor-annotation-manager 	Desired: 1	Ready: 1	Available: 1
Containers :
 	kubearmor-policy-manager-678bd94bd-rlzmn     	Running: 2	Image Version: arrowhalo/kube-rbac-proxy:v0.8.0
 	kubearmor-relay-6fddb8865b-kdxmj             	Running: 1	Image Version: kubearmor/kubearmor-relay-server:latest
 	kubearmor-host-policy-manager-d577d8f6c-xpn2n	Running: 2	Image Version: arrowhalo/kube-rbac-proxy:v0.8.0
 	kubearmor-8cqsh                              	Running: 1	Image Version: kubearmor/kubearmor:stable
 	kubearmor-lgbtf                              	Running: 1	Image Version: kubearmor/kubearmor:stable
 	kubearmor-annotation-manager-8cff75984-kgs5j 	Running: 2	Image Version: arrowhalo/kube-rbac-proxy:v0.8.0
Node 1 :
 	OS Image:                 	Alibaba Cloud Linux 3 (Soaring Falcon)
 	Kernel Version:           	5.10.134-12.al8.x86_64
 	Kubelet Version:          	v1.25.2+k3s1
 	Container Runtime:        	containerd://1.6.8-k3s1
 	Active LSM:               	BPFLSM
 	Host Security:            	true
 	Container Security:       	true
 	Container Default Posture:	block(File)                           	block(Capabilities)	block(Network)
 	Host Default Posture:     	block(File)                           	block(Capabilities)	block(Network)
Node 2 :
 	OS Image:                 	Alibaba Cloud Linux 3 (Soaring Falcon)
 	Kernel Version:           	5.10.134-12.al8.x86_64
 	Kubelet Version:          	v1.25.2+k3s1
 	Container Runtime:        	containerd://1.6.8-k3s1
 	Active LSM:               	BPFLSM
 	Host Security:            	true
 	Container Security:       	true
 	Container Default Posture:	block(File)                           	block(Capabilities)	block(Network)
 	Host Default Posture:     	block(File)                           	block(Capabilities)	block(Network)
Armored Up pods :
+-------------+--------------------------------------+-----------------------------+
|  NAMESPACE  |                 NAME                 |           POLICY            |
+-------------+--------------------------------------+-----------------------------+
| multiubuntu | ubuntu-2-deployment-76b456cd9d-kqhfd |                             |
+             +--------------------------------------+-----------------------------+
|             | ubuntu-5-deployment-84dc8fdbd7-4m7f7 | ksp-group-1-proc-path-block |
+             +--------------------------------------+-----------------------------+
|             | ubuntu-1-deployment-56df5dd784-fw44w |                             |
+             +--------------------------------------+-----------------------------+
|             | ubuntu-3-deployment-9fc57b5f6-6dpdn  |                             |
+             +--------------------------------------+-----------------------------+
|             | ubuntu-4-deployment-668bfbd889-g2vtq | ksp-group-1-proc-path-block |
+             +--------------------------------------+-----------------------------+
|             | test-585cbdcf64-wlgcc                | ksp-group-1-proc-path-block |
+             +--------------------------------------+-----------------------------+
|             | test-585cbdcf64-zrh9w                | ksp-group-1-proc-path-block |
+-------------+--------------------------------------+-----------------------------+
```

<img width="1358" alt="image" src="https://user-images.githubusercontent.com/19342276/200810067-e6c49c15-321d-44fe-8afc-ee1093a81ead.png">



# the KubeArmorPolicy is

```yaml
apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-group-1-proc-path-block
  namespace: multiubuntu
spec:
  severity: 5
  message: "block /bin/sleep"
  selector:
    matchLabels:
      group: group-2
  process:
    matchPaths:
    - path: /bin/cat
  action:
    Block

# multiubuntu_test_01

# test
# $ sleep 1
# bash: /bin/sleep: Permission denied
```
# test yaml

```bash
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
  namespace: multiubuntu
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      group: group-2
  template:
    metadata:
      labels:
        group: group-2
    spec:
      terminationGracePeriodSeconds: 0
      # affinity:
      #   podAntiAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #     - topologyKey: kubernetes.io/hostname
      #       labelSelector:
      #         matchLabels:
      #           group: group-2
      containers:
      - name: busybox
        image: nicolaka/netshoot
        command: ["/bin/sh"]
        args: ["-c", "tail -f /dev/null"]
```

# but only ubuntu-5 and  ubuntu-4 can block , two test pods can not block 

<img width="697" alt="image" src="https://user-images.githubusercontent.com/19342276/200810476-4d1aeb9e-1b1a-4e34-8636-ef79633b228e.png">

<img width="991" alt="image" src="https://user-images.githubusercontent.com/19342276/200810573-17f811eb-0039-48d9-a785-583eb086e126.png">
