### ISSUE TITLE
Invalid apply of ksp - problem with using selector labels

### ISSUE THREAD

**Issue by nyrahul** [kubearmor/KubeArmor#983]
## Bug Report

Selector labels construct in the policy tells the kubearmor which pods the corresponding policy has to be applied on.

Consider [wordpress-mysql example](https://github.com/kubearmor/KubeArmor/tree/main/examples/wordpress-mysql):

kubectl apply -f policy.yaml
```yaml
apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-wordpress-block-process
  namespace: wordpress-mysql
spec:
  severity: 3
  selector:
    matchLabels:
      app: wordpress
      env: production
  process:
    matchPaths:
    - path: /usr/bin/apt
    - path: /usr/bin/apt-get
  action:
    Block
```

Note that the wordpress deployment does not have the label `env: production` but still the policy is applied as shown by `karmor probe`.

```
Armored Up pods : 
+-----------------+---------------------------------+-----------------------------+
|    NAMESPACE    |              NAME               |           POLICY            |
+-----------------+---------------------------------+-----------------------------+
| wordpress-mysql | mysql-58cdf6ccf-z9hpc           |                             |
+                 +---------------------------------+-----------------------------+
|                 | wordpress-bf95888cb-56x8j       | ksp-wordpress-block-process |
+-----------------+---------------------------------+-----------------------------+
```

**To Reproduce**

1. apply the policy.yaml
2. check `karmor probe`

**Expected behavior**

`karmor probe` should not show policy applied in the context of wordpress pods.
