### ISSUE TITLE
Audit based policy not working with readonly rule

### ISSUE THREAD

**Issue by Ankurk99** [kubearmor/KubeArmor#989]
## Bug Report

If we have a audit based policy with "readonly" rule then we are not getting alert for the rule denial

**To Reproduce**
1) Apply the following policy
```
apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: wordpress-wordpress-4-8-apache-system-monitoring-write-under-dev-directory
  namespace: wordpress-mysql
spec:
  action: Audit
  file:
    matchDirectories:
    - dir: /dev/
      readOnly: true
      recursive: true
  message: Alert! File creation under /dev/ directory detected.
  selector:
    matchLabels:
      app: wordpress
  severity: 5
  tags:
  - NIST
  - NIST_800-53_AU-2
  - NIST_800-53_SI-4
  - MITRE
  - MITRE_T1036_masquerading
```
2) Exec into the wordpress pod and create a directory inside `/dev/` folder: `touch /dev/abc`

**Expected behavior**
The above action should have created an alert for illegal file creation as the `/dev/` path is readonly
Audit alerts should be visible for readonly rule
