### ISSUE TITLE
KubeArmor not generating alerts for policies with binary `mv`

### ISSUE THREAD

**Issue by vishnusomank** [kubearmor/KubeArmor#998]
## Bug Report

**General Information**

- Environment: k3s
- Kernel version : 
    ```sh
    Linux zero-knox 5.15.0-52-generic #58-Ubuntu SMP Thu Oct 13 08:03:55 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
    ```
- kubectl version
    ```sh
    Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.11", GitCommit:"dc2898b20c6bd9602ae1c3b51333e2e4640ed249", GitTreeState:"clean", BuildDate:"2022-09-14T16:40:13Z", GoVersion:"go1.17.13", Compiler:"gc", Platform:"linux/amd64"}
    Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.9+k3s1", GitCommit:"f45cf3267307b153ed8b418ae5b8ea6c6b9ebaca", GitTreeState:"clean", BuildDate:"2022-07-19T00:42:17Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}
    ```

- Policy file
    ```yaml
    apiVersion: security.kubearmor.com/v1
    kind: KubeArmorPolicy
    metadata:
      name: wordpress-wordpress-test-1
      namespace: wordpress-mysql
    spec:
      action: Block
      file:
        matchPaths:
        - path: /root/.bash_history
          fromSource:
          - path: /usr/bin/shred
          - path: /usr/bin/rm
          - path: /bin/mv
          - path: /bin/rm
          - path: /usr/bin/mv
        - path: /home/*/.bash_history
          fromSource:
          - path: /usr/bin/shred
          - path: /usr/bin/rm
          - path: /bin/rm
          - path: /bin/mv
          - path: /usr/bin/mv
      message: Alert! bash history modification or deletion detected and prevented
      selector:
        matchLabels:
          app: wordpress
      severity: 5
      tags:
      - NIST
      - NIST_800-53
      - NIST_800-53_CM-5
      - NIST_800-53_AU-6(8)
      - MITRE_T1070_indicator_removal_on_host
      - MITRE
      - MITRE_T1036_masquerading
    ```
- Target pod: `wordpress-765f89bf9f-vrfxf`

**To Reproduce**

1. Deploy wordpress application [ref](https://github.com/kubearmor/KubeArmor/blob/main/examples/wordpress-mysql/wordpress-mysql-deployment.yaml)
2. Apply the above mentioned policy
3. Execute into the wordpress pod and perform the following actions
    ```sh
    root@wordpress-765f89bf9f-b52bh:~# shred /root/.bash_history 
    root@wordpress-765f89bf9f-b52bh:~# mv /root/.bash_history /home/history
    root@wordpress-765f89bf9f-b52bh:~# rm /root/.bash_history              
    ```
4. Watch karmor logs
    ```sh
    karmor log --json | jq .
    ```

**Expected behavior**

Permission denied message on the shell with a corresponding `Permission denied` alert generated for each `shred`, `rm` and `mv` operation on `/root/.bash_history`

**Current behavior**

The operation is getting denied but no alerts are getting generated for `mv`

**Telemetry data:**

**on shell**

  ```sh
  root@wordpress-765f89bf9f-b52bh:~# shred /root/.bash_history 
  shred: /root/.bash_history: failed to open for writing: Permission denied
  root@wordpress-765f89bf9f-b52bh:~# mv /root/.bash_history /home/history
  mv: cannot move '/root/.bash_history' to '/home/history': Permission denied
  root@wordpress-765f89bf9f-b52bh:~# rm /root/.bash_history              
  rm: cannot remove '/root/.bash_history': Permission denied
  
  ```

**karmor log**

```json
{
  "Timestamp": 1668760959,
  "UpdatedTime": "2022-11-18T08:42:39.242796Z",
  "ClusterName": "default",
  "HostName": "zero-knox",
  "NamespaceName": "wordpress-mysql",
  "PodName": "wordpress-765f89bf9f-b52bh",
  "Labels": "app=wordpress",
  "ContainerID": "936ac66c54bad96a754c23badbd4645b10fc0f88ffe8bc7445bf09a86f91ce46",
  "ContainerName": "wordpress",
  "ContainerImage": "wordpress:4.8-apache@sha256:6216f64ab88fc51d311e38c7f69ca3f9aaba621492b4f1fa93ddf63093768845",
  "HostPPID": 129009,
  "HostPID": 131483,
  "PPID": 193,
  "PID": 209,
  "ParentProcessName": "/bin/bash",
  "ProcessName": "/usr/bin/shred",
  "PolicyName": "wordpress-wordpress-test-1",
  "Severity": "5",
  "Tags": "NIST,NIST_800-53,NIST_800-53_CM-5,NIST_800-53_AU-6(8),MITRE_T1070_indicator_removal_on_host,MITRE,MITRE_T1036_masquerading",
  "ATags": [
    "NIST",
    "NIST_800-53",
    "NIST_800-53_CM-5",
    "NIST_800-53_AU-6(8)",
    "MITRE_T1070_indicator_removal_on_host",
    "MITRE",
    "MITRE_T1036_masquerading"
  ],
  "Message": "Alert! bash history modification or deletion detected and prevented",
  "Type": "MatchedPolicy",
  "Source": "/usr/bin/shred /root/.bash_history",
  "Operation": "File",
  "Resource": "/root/.bash_history",
  "Data": "syscall=SYS_OPEN flags=O_WRONLY|O_NOCTTY",
  "Enforcer": "AppArmor",
  "Action": "Block",
  "Result": "Permission denied"
}
{
  "Timestamp": 1668760985,
  "UpdatedTime": "2022-11-18T08:43:05.832954Z",
  "ClusterName": "default",
  "HostName": "zero-knox",
  "NamespaceName": "wordpress-mysql",
  "PodName": "wordpress-765f89bf9f-b52bh",
  "Labels": "app=wordpress",
  "ContainerID": "936ac66c54bad96a754c23badbd4645b10fc0f88ffe8bc7445bf09a86f91ce46",
  "ContainerName": "wordpress",
  "ContainerImage": "wordpress:4.8-apache@sha256:6216f64ab88fc51d311e38c7f69ca3f9aaba621492b4f1fa93ddf63093768845",
  "HostPPID": 129009,
  "HostPID": 131709,
  "PPID": 193,
  "PID": 211,
  "ParentProcessName": "/bin/bash",
  "ProcessName": "/bin/rm",
  "PolicyName": "wordpress-wordpress-test-1",
  "Severity": "5",
  "Tags": "NIST,NIST_800-53,NIST_800-53_CM-5,NIST_800-53_AU-6(8),MITRE_T1070_indicator_removal_on_host,MITRE,MITRE_T1036_masquerading",
  "ATags": [
    "NIST",
    "NIST_800-53",
    "NIST_800-53_CM-5",
    "NIST_800-53_AU-6(8)",
    "MITRE_T1070_indicator_removal_on_host",
    "MITRE",
    "MITRE_T1036_masquerading"
  ],
  "Message": "Alert! bash history modification or deletion detected and prevented",
  "Type": "MatchedPolicy",
  "Source": "/bin/rm /root/.bash_history",
  "Operation": "File",
  "Resource": "/root/.bash_history",
  "Data": "syscall=SYS_UNLINKAT flags=",
  "Enforcer": "AppArmor",
  "Action": "Block",
  "Result": "Permission denied"
}
```
